### ISSUE TITLE
Used WiredTiger instead of MMAP

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#162]
Instructions for switching to WiredTiger: https://docs.mongodb.com/v3.0/release-notes/3.0-upgrade/#change-storage-engine-to-wiredtiger

**Comment by distalx** [comment]
Right now we are using a sandbox db at MLab, and I believe they have already migrated all the sendbox db to WiredTiger. 

We should consider switching to shared cluster once we go live !
