### ISSUE TITLE
Countdown to hangout (instead of saying "Upcoming in 2 minutes," count it down)

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#173]
@leewaygroups suggested this idea:

Instead of having static text saying "Upcoming in 2 minutes," we could have an interactive countdown timer.

Relevant SO links (maybe)? http://stackoverflow.com/questions/16129157/countdown-timer-using-moment-js

**Comment by sgtphips** [comment]
Adding a link to the moment-countdown plugin
https://github.com/icambron/moment-countdown

**Comment by lpatmo** [comment]
Below is an example of where we could replace the "Upcoming in X hours" with a dynamic countdown:

![screen shot 2016-09-28 at 1 02 42 am](https://cloud.githubusercontent.com/assets/4512699/18905307/5a33a0e8-8517-11e6-908a-109434caba35.jpg)

**Comment by christiansafka** [comment]
I can do this.  Does someone else need to assign me?  I'm new to open source.

**Comment by adachiu** [comment]
@christiansafka You can assign yourself so that we know who is working on this issue. Thanks!

**Comment by christiansafka** [comment]
@adachiu Can you add me as a contributor?  Or else I can't assign myself.

**Comment by lpatmo** [comment]
@christiansafka I added you as a collaborator! After this, though, I think we're going to start phasing out the use of the "assignees" feature on the right so that folks don't have to wait a while to be added before they can assign themselves to an issue. A comment indicating that you're interested in/are going to start working on the issue in Branch X should be fine. :) 

@christiansafka You can `git clone` this repo, or fork it and clone your own repo. Let us know if you have any other questions about this issue. Thanks!

**Comment by lpatmo** [comment]
@christiansafka If you're still planning on working on this issue, do you need any help with it? Let us know!

**Comment by christiansafka** [comment]
@lpatmo Hey, I had some problems installing Meteor when I was going to fix this, and now do not have time for anything.  Sorry!  Issue is open to anyone.

**Comment by lpatmo** [comment]
@christiansafka Thanks for letting us know! I will add back the `not-claimed` label.

**Comment by abhiii5459** [comment]
@distalx This is the issue that's the original of the one I opened right? #286 . May I take this one?

**Comment by distalx** [comment]
Sure. :)

**Comment by sergeant-q** [comment]
@abhiii5459 this has been deployed to `master` correct? Can we close this issue?

**Comment by distalx** [comment]
Yes @sergeant-q
