### ISSUE TITLE
Add "Learnings" section to each single post

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#201]
- [ ] 1. On each hangout post, add a textarea\* that lets users submit notes about what they learned during the hangout.
- [ ] 2. The single post page will also display all the "learnings" in that hangout.
- [ ] 3. The learnings will also feed into the global "learnings/accomplishments" tab on the home page.

Having this will be nice for those who want to keep track of their progress, or at least take notes on what they're learning.

*Add QuillJS to textarea, maybe!

**Comment by jsoranno** [comment]
I'd like to try it!

**Comment by distalx** [comment]
@jsoranno It's yours! I will change the `claimed` label. Thanks!

**Comment by jsoranno** [comment]
@distalx I'm going to have to learn Meteor first! I'll give this one back to the community now. I'll be back!

**Comment by lpatmo** [comment]
@jsoranno Do you need any help with this issue? Let us know! :)

**Comment by abhiii5459** [comment]
@distalx @jsoranno we can work together on this and you can make it your first PR if you like :)

**Comment by jsoranno** [comment]
That would be awesome!

**Comment by distalx** [comment]
some ideas for ui.
For notes and accompaniment we could place an icon for each, aside hangout.
<img width="320" alt="screen shot 2016-10-07 at 9 13 20 pm" src="https://cloud.githubusercontent.com/assets/11193792/19200042/96689ed6-8ce4-11e6-819a-02d1c8d110e1.png">

On click, icons could pop a modal view. 

Notes
<img width="833" alt="screen shot 2016-10-07 at 11 26 55 pm" src="https://cloud.githubusercontent.com/assets/11193792/19200253/a5c6c096-8ce5-11e6-84e9-3aa339e93caa.png">

Accomplishments
<img width="334" alt="screen shot 2016-10-07 at 11 27 17 pm" src="https://cloud.githubusercontent.com/assets/11193792/19200276/bab942b2-8ce5-11e6-8982-1e6a31e31c7d.png">

**Comment by lpatmo** [comment]
Sorry for the slow follow-up on this.

I think the UI ideas are interesting, but to start, it'd be easier if we simplified it and put a `learnings` textarea with submit button next to the `comments` textarea -- maybe a 50-50 grid, though other design ideas are welcome.

@jsoranno Are you still interested in working on this issue in a hangout? And are you by any chance free tomorrow? If you're not interested in working on this anymore, no worries -- please let us know. Sorry it's been a week!

**Comment by jsoranno** [comment]
Sorry - I just wasn't able to carve out time. Hopefully someone else can do it for Hacktoberfest!

**Comment by tekhaus** [comment]
I'd like to tackle this

**Comment by lpatmo** [comment]
@jsoranno No worries -- thanks for trying!
