### ISSUE TITLE
`meteor reset` is necessary for people who have existing data and hadn't updated in a while

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#213]
Will's avatar didn't show up when he logged in at localhost:3000 because he had old data for his `user` with an old data structure.

Solved by deleting the user (or a `meteor reset`).

Question is: will this bite users on the live site if they had signed up a few months ago, but hadn't logged in since the schema change? 

I think most users didn't sign up until _after_ the schema change, so we're all right.

**Comment by William-R-Wilson** [comment]
What would be the impact of doing a function call when people log in to see if their current data matches the new schema, and pull new data if it's the old schema?
