### ISSUE TITLE
HTML/CSS: Add "video with slash" icon next to "silent microphone" icon.

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#30]
Just to make it clear to people that google hangouts don't involve video. :) (Unless the host or a participant really wants to show their face.)

**Comment by adachiu** [comment]
I suggest we stick with material design icons for the whole app if we're going to use the "video with slash" icon from material's icon collection. So we don't mix fontawesome and material design icons (mixing may look inconsistent).

**Comment by techtolentino** [comment]
Is this done or still needed?
