### ISSUE TITLE
Feature request: user profile should have a follow button.

### ISSUE THREAD

**Issue by distalx** [codebuddiesdotorg/codebuddies#316]
Presently, it’s not possible to receive an alert when specific host creates a hangout.

Add a button to the user profile that let others follow/unfollow that user.
Followers will receive an updates on when host creates an hangout.

Alert could be either a notification or an email. Or it could be both.

**Comment by lpatmo** [comment]
I think it makes more sense to "subscribe" to new hangouts created within a study group, rather than to subscribe to specific users. Closing this.
