### ISSUE TITLE
Volunteers descriptions are just lorem ipsum

### ISSUE THREAD

**Issue by gytdau** [codebuddiesdotorg/codebuddies#321]
On the bottom of https://codebuddies.org/about - under the heading `And all those who've made a positive impact on the project and the community`, everyone's popup box is a paragraph of filler text and a generic username. The links don't go anywhere meaningful either.

Did we originally plan to have a system where people fill this info in?

**Comment by lpatmo** [comment]
@gytdau Heh, yes -- sorry, that's on me! I have to finish contacting everyone and make sure they're okay with their descriptions / notes about how they've helped.

**Comment by gytdau** [comment]
Oh, okay. That sounds difficult to coordinate - maybe we should have a unified form for everyone?

**Comment by adachiu** [comment]
@lpatmo I created a Google Form for collecting CodeBuddies volunteer descriptions. Shared it with you already. Perhaps you can pin the link to `codebuddies-meta` channel using the `@channel` so you don't have to ask each volunteer to submit information.

**Comment by lpatmo** [comment]
Thanks @adachiu! Maybe we can add it to `contributing.md` as one of the last steps, for those who want their information added to the `Contributors` list.

**Comment by foxiae** [comment]
@lpatmo I think that goes along with what we all talked about in Slack a couple of weeks ago. I'll template something up in contributing.md and submit it in.

**Comment by foxiae** [comment]
Actually... I was thinking. If we have people edit both files, when they go do their PR, wouldn't there be a merge conflict? (Just seems like it'll produce a huge headache.)

Would a possible workflow be:
1. Create branch
2. Work and commit stuff
3. If it's been less than 3 days (just an example), merge master changes into your branch
4. Submit PR
5. Once PR has been approved, merge master changes again
6. Edit contributing files
7. Merge branch into master

**Comment by lpatmo** [comment]
Makes sense generally, though I have a question about step 6 -- are you suggesting that contributors add their information to the /about page themselves, instead of submitting their info to the google form Ada started?

**Comment by foxiae** [comment]
I was also thinking we could just have a standing branch for contributing files, and they could just commit there. Then we can do periodic releases of it.
Yes. We can template out the HTML and have them update the information - with instruction. (This is for new contributors. The ones existing on the page now, the Google Forms will work and we can paste the information in.) It would save work on us inputting the stuff in and all we have to do is review the work. If it gets *too* overloaded, we can do something like how my local Rails group handles the community: http://bmoreonrails.org/. The user profile images are randomly generated on refresh.
