### ISSUE TITLE
Add link to https://codebuddiesmeet.slack.com/messages/@username1,username2,username3,username3/ on single hangout post page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#371]
Note: before this issue can be tackled, #370 need to be completed.

For hangouts, I've noticed that it's been useful to start a group chat between all the participants -- just in case someone is late, or needs to cancel last-minute, or even simply as a reminder that a hangout is happening.

On a single post page like https://codebuddies.org/hangout/foy5uGm9S7yitgE9o, let's add a button that says "DM all participants on Slack". The button should link to something like this: `https://codebuddiesmeet.slack.com/messages/@username1,username2,username3,username3/`

On Slack, this automatically creates a private group chat between the usernames.

Note that before this issue can be tackled, #370 needs to be resolved, since if only one of the usernames is invalid, the entire link breaks and the user is redirected back to the #general channel.

**Comment by newswim** [comment]
reference: https://api.slack.com/methods/chat.postMessage

**Comment by sergeant-q** [comment]
I think it would be better if we leveraged Slack's API to create a group chat. Creating a link such as the one recommended might be too brittle and as you noted @lpatmo can create undesired behavior for the user.

I found the **multi-party im** method: https://api.slack.com/methods/mpim.open that we should be able to call. However there is a limitation of up to **8** users it can open a new group chat with. I am not sure if the URL approach has the same limitation.  We will also need to install a separate NPM package that provides us with this functionality. Here is [one](https://www.npmjs.com/package/slack) I think may be suitable. 

## Items to discuss
 - Can we live with the 8 user group chat limitation?
 - Do we have any stats that show we normally average more than 8 participants per hangout?

Open to further discussions, feedback or general thoughts!

**Comment by lpatmo** [comment]
> Can we live with the 8 user group chat limitation?

Yes, an 8-user group chat limitation is fine! We usually don't have more than 6 people in a hangout. :)

**Comment by lpatmo** [comment]
I'm going to close this issue, since:
- users are able to join the Jitsi hangout before the official start of the hangout now, and use the chat interface to chat
- user RSVPs to a hangout are publicly displayed in the #announcement alert and folks can follow up individually with other participants pretty easily; no need to do a lot of work to build a group chat integration, I think.

Thanks for all of your thoughts on this last year!
