### ISSUE TITLE
Should we change the name of our repo to `codebuddies` instead of `cb-v2-scratch`?

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#424]
Just a thought, so that when clone or fork it you can type `cd codebuddies` instead of `cd cb-v2-scratch`

**Comment by foxiae** [comment]
^^ In case it wasn't obvious, I agree 100000%. Will we need to reset the upstream branch on our local machines?

**Comment by lpatmo** [comment]
lol. Yeah, I think:
- the upstream branch will need to updated
- links need to be changed to reference `https://github.com/codebuddiesdotorg/codebuddies`

**Comment by lpatmo** [comment]
Note: once we change the names, everyone will have to do this:
```
git remote set-url origin git@github.com:codebuddiesdotorg/cb-v2-scratch.git
```

And then everyone needs to check that they have the correct origin URL set:
```
git remote -v
```

**Comment by lpatmo** [comment]
I made the change!

Please run the commands above.

**Comment by wuworkshop** [comment]
If you forked the repo, then you update your `origin` branch like this:
```
git remote set-url origin git@github.com:YOUR-GITHUB-USERNAME/codebuddies.git
```

And update your `upstream` branch like this:
```
git remote set-url upstream git@github.com:codebuddiesdotorg/codebuddies.git
```

Then verify the changes were updated with:
```
git remote -v
```

**Comment by sergeant-q** [comment]
This is completed.
