### ISSUE TITLE
Removing commented out code

### ISSUE THREAD

**Issue by ericathedev** [codebuddiesdotorg/codebuddies#427]
When fixing my first issue I saw some commented out code. 

It is usually good practice to avoid commented code so as to maintain clean coding standards/avoid code rot 👻. 

Is it okay if I remove any existing commented out code?

**Comment by ericathedev** [comment]
If you agree that this is needed I would love to do it 😸 .

**Comment by lpatmo** [comment]
@ericathedev In general, yes! Thank you! My only flag is that if the commented out code is useful in some way, it's probably a good idea to keep it in with a comment about why it's a good reference.

**Comment by ericathedev** [comment]
@lpatmo okay thanks! Then I will start submitting some small code deletions for easier review, if I accidentally remove a useful piece of commented code please flag it in the pull request? 😸

**Comment by lpatmo** [comment]
@ericathedev Of course! :)

**Comment by wuworkshop** [comment]
Looks like this issue can be closed.
