### ISSUE TITLE
"CodeBuddies Alerts" (BOT) Time Bug

### ISSUE THREAD

**Issue by AndreSchwarzer** [codebuddiesdotorg/codebuddies#438]
# Do you want to request a feature or report a bug?

Bug

# What is the current behavior?

Incorrect remaining time / time until event starts.

# What is the expected behavior?

Correct remaining time / time until event starts. 😃 

# Which browser / OS are affected by this issue?

All. It is a general problem.

See images attached.

# Images

## Notification
![notification](https://cloud.githubusercontent.com/assets/6991100/22145810/19b189e0-df03-11e6-8164-25caa0ede99c.png)

## Bug
![bug](https://cloud.githubusercontent.com/assets/6991100/22145822/2268aeec-df03-11e6-88e5-73b66d49283d.png)

**Comment by coltonehrman** [comment]
Working on this.
