### ISSUE TITLE
Start archiving important Slack messages/links

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#440]
Came up in the #codebuddies-meta hangout with @BethanyG and @distalx on January 24th:
- Let's archive some links/messages
- Case study: CodeSelfStudy (raw dump of data)
- Could we tag/favorite certain messages that we want to save?

**Comment by BethanyG** [comment]
First crack at this:
[**Outgoing webhooks:**  ](https://api.slack.com/outgoing-webhooks)

> Outgoing webhooks will send an HTTP POST request to your specified URL when a message matches one or both of the following conditions:
> -  The message is in the specified channel _(only works in public channels & is subject to rate limit)_
> -  The message begins with one of the defined trigger word(s) _(works anywhere)_
>

Setting a keyword or /   trigger (i.e. /archive or /save or /remember) that will only archive what's flagged is what codeselfstudy has done with the keyword "Tag", I think.

So we could POST what we wanted to save to an API on codebuddies.org - and either  stuff it in Mongo, or do something automated with it like posting it to a wiki, or a running list, or some other organizational thing we decide.  The only question I have is if URLs are considered attachments.  Attachments to messages are not included in outgoing webhooks, so file uploads and (possibly) code snippets wouldn't be included.

**Comment by BethanyG** [comment]
Another thought is, of course, a bot that could both use the outgoing webhook for messages, but also use the full Slack API to do things like export files and attachments.

**Comment by BethanyG** [comment]
And one last one:  [](https://levels.io/slack-export-to-html/ ) is a script to use Slacks Export feature to dump all public content out and convert it to HTML.  So I am thinking a chron job could be set up do use something like this at a weekly (?) interval to export things, convert them to HTML, and .... post them to a wiki?  Make static pages?  I don't know....

**Comment by stain88** [comment]
An alternative: [http://slackarchive.io](http://slackarchive.io)

**Comment by lpatmo** [comment]
Wow -- that might very well suit our purposes! Thanks for the find, @stain88! What does everyone else think?

**Comment by wuworkshop** [comment]
Closing this issue since slackarchive.io has been set up.
