### ISSUE TITLE
Detect user language to take advantage of i18n translations

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#446]
@osanseviero added an es.i18n.json file, which means we now have the capacity to translate to Spanish. 

According to https://github.com/TAPevents/tap-i18n#quickstart, we need to detect the language used by the user:
```
getUserLanguage = function () {
  // Put here the logic for determining the user language

  return "sp";
};

if (Meteor.isClient) {
  Meteor.startup(function () {
    Session.set("showLoadingIndicator", true);

    TAPi18n.setLanguage(getUserLanguage())
      .done(function () {
        Session.set("showLoadingIndicator", false);
      })
      .fail(function (error_message) {
        // Handle the situation
        console.log(error_message);
      });
  });
}
```

Will research later how to do this.

**Comment by osanseviero** [comment]
Is there any work being done related to this?

**Comment by ajparise** [comment]
No idea if this is still relevant.
Found a pretty good article here related to auto-setting the language.
https://themeteorchef.com/tutorials/i18n-and-meteor#tmc-auto-setting

**From that I came up with this**
```javascript
  Meteor.startup(function () {
    ...
    const defaultLang = 'en'

    // grab language from query param
    const urlLang = FlowRouter.getQueryParam('lang')

    // grab language from the browser
    // removes the region  fr-CA -> fr, en-US -> en
    const browserLang = (window.navigator.userLanguage || window.navigator.language || '').slice(0,2)

    TAPi18n.setLanguage(urlLang || browserLang || defaultLang)
  });
```

![image](https://user-images.githubusercontent.com/2686067/32978155-62e21a54-cc0a-11e7-8a43-f3a5ee36657b.png)

**Comment by osanseviero** [comment]
Oh, wow. Great work! 

@lpatmo what do you think?
