### ISSUE TITLE
Jitsi testing on Windows machines (Chrome and Firefox)

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#455]
We need to make sure Jitsi (https://codebuddies.herokuapp.com/hangout/JcAkTyHixM3oPPSQT) loads and has good audio + screensharing from Windows machines. 

Chrome - @ycodebuddies tested on Windows 8.1 and confirms audio + screensharing works
Firefox - @ycodebuddies tested on Windows 8.1 and confirms audio + screensharing works
Microsoft Edge - not yet formally tested, but heard there were problems from @texrat

**Comment by stain88** [comment]
Don't think there's anything to do for Microsoft, based on [this thread](http://markmail.org/message/7ps2swm7rywjtupx#query:+page:1+mid:7ps2swm7rywjtupx+state:results) (admittedly from almost a year ago) the plugin jitsi uses isn't compatible with IE/Edge. Console on Edge throws quite a few errors along the lines of "Unable to get property of undefined"
