### ISSUE TITLE
Move hangouts that are in progress but not yet completed to the top

### ISSUE THREAD

**Issue by stain88** [codebuddiesdotorg/codebuddies#458]
What is the current behavior?
Hangouts on the homepage are listed, presumably in order of creation, but with the furthest date at the top.

What is the expected/_wished for_ behavior?
Hangouts should be sorted by completion date/time, with the closest future date at the top, and all hangouts-to-be above completed ones

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
All

**Comment by newswim** [comment]
FWIW, the same behavior you describe is on Firefox, Safari and Chrome - I think this is just an issue with the ordering. This is the order that makes sense to me, let me know what you think and if there any exceptions that should be made.

```
<soonest>
<less soon>
<completed>
```

**Comment by wuworkshop** [comment]
@newswim Per Slack conversation, this is all yours.
