### ISSUE TITLE
Padding for Home page "community hangouts" section

### ISSUE THREAD

**Issue by adachiu** [codebuddiesdotorg/codebuddies#464]
The community hangouts section needs padding to be added.

1. Padding above title "Community Organized Hangouts"
2. Padding around the text inside each hangout box

<img width="1401" alt="screen shot 2017-03-11 at 4 29 51 pm" src="https://cloud.githubusercontent.com/assets/13413986/23828020/57177d20-0678-11e7-812b-43842a91eceb.png">

**Comment by stain88** [comment]
Hmm, the css is there, looks like that section got missed during commit 3aba4e4

**Comment by lpatmo** [comment]
Thanks for the issue, @adachiu and nice sleuthing, @stain88! 

Yes it looks like the `padding: 0 30 40` in `_home.scss` was missed (supposed to be 0px 30px 40px) and what happened to the margin above "Community-organized hangouts", but should be `margin-top: 40px` or something added above `#home .home-middle h2` in `_home.scss` file as well.

Good issue for a beginner to tackle.

**Comment by morrme** [comment]
are these the two sections that need to be changed? 
![home middle](https://cloud.githubusercontent.com/assets/26514778/24096188/8aa34d88-0d2e-11e7-9e83-aa9c198be390.PNG)

and

![hangout cards](https://cloud.githubusercontent.com/assets/26514778/24096187/8aa31bce-0d2e-11e7-848d-4588389f5895.PNG)

**Comment by lpatmo** [comment]
@morrme Yep, that looks right! Were you able to get the app started up in your localhost:3000 from the contributing.md instructions, out of curiosity?

**Comment by morrme** [comment]
It is building now.

**Comment by morrme** [comment]
How does this look?

![464-fix-0](https://cloud.githubusercontent.com/assets/26514778/24137234/eac555a0-0de0-11e7-93bd-c68255af4bdf.PNG)

**Comment by lpatmo** [comment]
Looks excellent! :) When you resize the browser to be narrow, it should be ok too, right?

I think these changes are what @adachiu had in mind, but will let her chime in in case she has any thoughts I missed.

**Comment by morrme** [comment]
yes
![464-fix-1](https://cloud.githubusercontent.com/assets/26514778/24137462/d9d6effa-0de1-11e7-9d01-6cea7c5c7df0.PNG)

**Comment by lpatmo** [comment]
@morrme Perfect. :) Sorry, I should've said last night -- feel free to create a PR for this issue with your changes!

**Comment by morrme** [comment]
@lpatmo sure ! one more thing....the .home-middle is also missing "px" (see above response) . Can I add that one back in as well?

**Comment by lpatmo** [comment]
@morrme Yes, that makes sense! Thanks!
