### ISSUE TITLE
HOME PAGE: Add a screenshot and explanation of an example Jitsi hangout to the non-logged-in home page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#468]
Wow, I didn't think we're already at this day, but... Jitsi embedded on the page as a Google Hangout so far seems okay! And it's in good use!!! 

On the home page, we're lacking an explanation of what a user might expect after they create a hangout. We should show a screenshot of an embedded Jitsi hangout, sort of like this:

![screen shot 2017-03-11 at 11 22 25 am](https://cloud.githubusercontent.com/assets/4512699/23936759/125e6446-0911-11e7-8589-55f4a4704247.jpg)

Or maybe we can recreate a better-looking screenshot. 

Maybe the process of scheduling a hangout and clicking the button to load the Jitsi hangout on the page could be a 5-second gif?? 

Not sure, but we need something.

**Comment by lpatmo** [comment]
Or maybe separate this out into two tasks:

1) Add screenshot showing the Jitsi hangout
2) Add screenshot showing the "create hangout" popup form to signify the idea that anyone can schedule/start a hangout.

**Comment by lpatmo** [comment]
We should also try to make it clear on the home page that hangouts are NOT "video calls" but tend to be "screensharing" meetings looking at code. I think too many people, when they hear "hangouts", still think of a google hangout video call and are thus shy about joining.

**Comment by lpatmo** [comment]
File to edit to put the screenshot: `templates/home/home_logged_out.html`

**Comment by grfraser** [comment]
**I will offer to work on this.** I forgot, sorry-I know I read it somewhere- **how do I claim this issue?** @lpatmo 
I will do my best- I know I can add the image and description easily. I will try a GIF though as well and see what looks better.

**Comment by lpatmo** [comment]
I just marked this issue as claimed. Thanks @grfraser!!

**Comment by grfraser** [comment]
Thank you @lpatmo !
