### ISSUE TITLE
Consider updating the button text to say "Schedule a Hangout" instead of "Create a Hangout"

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#469]
Does anyone have strong opinions about this? I could go either way, but maybe leaning slightly towards it saying "Schedule a hangout"

![screen shot 2017-03-16 at 9 58 40 pm](https://cloud.githubusercontent.com/assets/4512699/24029498/c129668c-0a93-11e7-98f4-6a3aee171019.jpg)

**Comment by adachiu** [comment]
Sounds good to change it to "Schedule a Hangout"

**Comment by sergeant-q** [comment]
I like it. It's more intuitive to what the user will actually be doing.

**Comment by wuworkshop** [comment]
Sounds good to me.

Just a reminder, any changes in English should also be changed in Spanish (and any future languages that get added).

**Comment by lpatmo** [comment]
@wuworkshop Good call!

**Comment by morrme** [comment]
I'd like to help update the English version. I can update other localized versions with the correct/approved text.

**Comment by lpatmo** [comment]
@morrme It's yours if you'd like to take this issue! The files you should be looking at are `i18n/en.i18n.json` and `es.i18n.json`. Please take a look at https://github.com/codebuddiesdotorg/codebuddies/blob/master/contributing.md, and let us know if you have any questions. Thanks!

**Comment by morrme** [comment]
Great! Should "Create this Hangout" also be changed? 

For the ES version, what would be the approved text? I speak the language but nowhere near natively enough to make this call.

**Comment by lpatmo** [comment]
I think we can keep the keyword `{{_ "create_a_hangout"}}` in `client/templates/home/home.html` that references `"create_a_hangout": "Create a Hangout",` in `i18n/en.i18n.json`. In other words, let's just change the value in the en.i18n.json file. (Did I understand your question correctly?)

As for the spanish version -- no idea. :P I took Spanish for several years but I'm not a native speaker either. Have you joined the CodeBuddies Slack? I'm going to ask @osanseviero in the #codebuddies-meta channel.

**Comment by lpatmo** [comment]
UPDATE: Okay, @osanseviero responded very quickly on Slack and the correct translation en espanol es "Programa un hangout"

**Comment by morrme** [comment]
@lpatmo  I was referring to the next line of the file , another button that says "Create This Hangout"

![create hangouts](https://cloud.githubusercontent.com/assets/26514778/24085245/48956416-0cc6-11e7-9433-cd5e36370f6f.PNG)

Thanks for the ES translation ! :+1:

**Comment by lpatmo** [comment]
@morrme Ah, I see -- that's the text when someone clicks to clone/duplicate an existing hangout. Yes, I think that can be changed to "Schedule this hangout". Thanks for the clarification!

**Comment by morrme** [comment]
@lpatmo no problem ! i will be joining slack as well but would the ES translation of the next line be "Programa este hangout"  ? And do you want to keep the capitalization as it currently exists on each button?

**Comment by lpatmo** [comment]
Oh sorry, yes "Programa este Hangout" should be right. And yeah, good question on the capitalization not being standard... that could be a separate issue, but maybe let's start making "Hangout" with a capital H be the standard.

**Comment by morrme** [comment]
OK, I'll change these as per the issue, and if needed I can help with standardizing the rest.

**Comment by lpatmo** [comment]
Gracias!

**Comment by morrme** [comment]
¡De nada! All done! PR #474

**Comment by lpatmo** [comment]
@morrme 
![image](https://cloud.githubusercontent.com/assets/4512699/24086177/ff1c458c-0cc7-11e7-8b89-01972d771c9e.png)

@morrme Did you just join the CodeBuddies Slack as `rmcnair`, or is that somebody else?

**Comment by morrme** [comment]
No , I'll be joining as ` emmo`

`
