### ISSUE TITLE
Favicon may be missing

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#470]
@sergeant-q reports that the favicon is not showing up on the site, and is instead a blank document. If you're seeing the same thing, please comment.

**Comment by stain88** [comment]
Can confirm missing on chrome, firefox, safari.
The link is to `/images/cb-logo.svg`: 
a) Is there such an icon in the /public/ folder?
b) shouldn't a favicon be png, gif or ico only?

**Comment by lpatmo** [comment]
@stain88 Good points!

If you guys don't mind, I want to take on this issue (even though it's technically a beginner issue) because I think I can fix it fairly quickly. Going to create a new favicon and upload it to the site.

(Still not entirely sure why I was seeing a favicon while other people weren't.)

Update: turns out there are a lot more steps involved to creating a favicon than committing a single favicon.ico line now. Have submitted a PR here:
