### ISSUE TITLE
Consider updating the twitter and facebook featured images to be a screenshot of a hangout instead of the CB logo

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#473]
The CB logo looks kind of gigantic on the automated twitter feed: https://twitter.com/codebuddiesmeet

Wondering if we should change the featured image to be something like 

![screen shot 2017-03-18 at 11 23 16 am](https://cloud.githubusercontent.com/assets/4512699/24078807/270040e6-0c35-11e7-8988-ba25316c7447.jpg)

... or another screenshot of a hangout that members of the community actually participated in. 

Thoughts?

**Comment by morrme** [comment]
I agree.

**Comment by lpatmo** [comment]
Just created this screenshot:

![jitsi-example](https://cloud.githubusercontent.com/assets/4512699/24325551/4ba39a42-1158-11e7-8412-54bb30ad07c5.jpg)
