### ISSUE TITLE
Updated "Sorry, please sign in first" popup to include a link to register on Slack

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#477]
I'm already working on this as part of the `learnings` branch; just wanted to log the change here for archival purposes.

New:
![screen shot 2017-03-19 at 11 46 41 pm](https://cloud.githubusercontent.com/assets/4512699/24090582/d92ae450-0cfe-11e7-88ed-3bf6f0dd1ecd.jpg)
- includes a link to sign up for the CB Slack
- includes a screenshot of what you might see if you're not currently logged into any Slack accounts, and shows you what you need to type in

Before:
![screen shot 2017-03-19 at 11 48 07 pm](https://cloud.githubusercontent.com/assets/4512699/24090592/e4f3327e-0cfe-11e7-8602-4ea26bcdd4b1.jpg)

Slack signin has always been really confusing for a lot of new users, so maybe this will help a bit.

We also have a separate issue to start supporting Github signin, which will be a big improvement.

**Comment by morrme** [comment]
should the modal text include links to the privacy policy, etc when they're mentioned?

**Comment by lpatmo** [comment]
They're on the popups now, but I'm leaning towards thinking we don't need them. (They're a little obtrusive, and we don't see messages like that on other sites.)
