### ISSUE TITLE
Let users upvote their own learnings?

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#482]
Wondering if we should let users upvote their own learnings!

Thoughts:
- it's fun to upvote your own learning and to see that clickable blue arrow
- an inflated point for each learning doesn't really matter in the larger context

If anyone has strong opinions *against* letting users upvote their own learnings, happy to hear it and keep it the status quo.

**Comment by morrme** [comment]
Most social media platforms allow you to do that, and if it brings even a little more continued delight to users, why not? :)
