### ISSUE TITLE
Meta info for individual hangout pages

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#490]
I've noticed that if we share a link from a hangout (e.g. https://codebuddies.org/hangout/BFovPHAJHSR8Fgo5J) the share info isn't very useful:

![screen shot 2017-03-25 at 3 40 29 pm](https://cloud.githubusercontent.com/assets/4512699/24326733/32ef333e-1172-11e7-92ed-1995d254fddf.jpg)

There should be a way to add meta info to each individual post page, I think. Something like:

```
Template.hangout.onCreated(function(){
  var title = //title of hangout
  var metaInfo = {name: "description", content: "//hangout description"};
  DocHead.setTitle(title);
  DocHead.addMeta(metaInfo);
});
```

Edit: may need to specify `og` tags to get the right headers showing up in Facebook. http://stackoverflow.com/questions/37088134/how-do-i-add-simple-facebook-og-tags-in-meteor

**Comment by distalx** [comment]
I'm going to give it a try.
