### ISSUE TITLE
Automatically turns text starting with "http" in "learnings" section into URLs

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#492]
In the learnings sections of hangouts (e.g. https://codebuddies.org/hangout/c4a2WpcYX9AyTzamB), any text that starts with "http" or "https" should automatically be converted into an `<a href="X">X</a>` link.

Let's use regex and javascript to solve this instead of applying QuillJS to learnings' input boxes.

**Comment by lpatmo** [comment]
Javascript should be put in `learning-item.js`.

**Comment by distalx** [comment]
@lpatmo can this be closed?

**Comment by lpatmo** [comment]
Yes, thanks, closing!
