### ISSUE TITLE
"Learnings" No More: Change Section Title to "Things We Learned"

### ISSUE THREAD

**Issue by arturolei** [codebuddiesdotorg/codebuddies#495]
This is not a bug or feature request, but a clarification about nomenclature. On the Hangout page, there is a section called "Learnings." Is there are reason why we call this aspect "Learnings"? The term seems at best idiosyncratic, at worst strange.  

Instead of calling the section "Learnings", what about "Things We Learned"? 

"Things We Learned" seems more consonant with the prompt in the textbox which asks "What did you Learn?". 

Obviously, before acting on this issue or creating a branch, I would like to hear input from members of the community.

**Comment by lpatmo** [comment]
I think changing "Learnings" to "Things We Learned" is a good suggestion.

**Comment by grfraser** [comment]
I vote for "Lessons Learned".

**Comment by lpatmo** [comment]
> I think we should also change the newest "Learning" submitted to appear at the top rather than the bottom. Otherwise the dates are out of chronological order when clicking load more. Appearing at the top also makes more sense, as it is the most recent.

That sounds like a fair issue to tackle, but in my localhost:3000, I do see the most recent "learning" submitted appearing at the very top. 

> "Lessons Learned"

IMO "Lessons Learned" is more concise and I would agree with it if it were in an essay, but I think "Things We Learned" sounds friendlier and matches more with the prompt in the textbox ("What did you learn?"). "Lessons Learned" also sounds a bit like "lesson learned" which has a slight negative connotation. I'd vote to stick with "Things We Learned."

**Comment by lpatmo** [comment]
I'm going to work on this bug.
