### ISSUE TITLE
contributing.md Table of Contents link bug.

### ISSUE THREAD

**Issue by grfraser** [codebuddiesdotorg/codebuddies#496]
## This is my first issue so please feel free to let me know if I am doing something incorrectly. - not sure if this is an important issue.

**Do you want to request a feature or report a bug?**
_Bug_
**What is the current behavior?**
_Table of Contents 10-15 links do not work. Regarding 1-9, they work on first click but not afterwards unless page is refreshed._
**What is the expected behavior?**
_All Table of Contents links should work appropriately, and they should work regardless of whether they have already been clicked._
**Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)**
_I am using Mac OS Sierra 10.12.4, Google Chrome Browser._

**Comment by morrme** [comment]
@lpatmo It's an issue with how the headers are written in some of the later sections. I can clean them up if you'd like.

**Comment by lpatmo** [comment]
Thanks, @morrme. I'll mark this issue as claimed!
