### ISSUE TITLE
adding-contributor link in contributing.md leads to 404, adding-contributor branch no longer exists.

### ISSUE THREAD

**Issue by grfraser** [codebuddiesdotorg/codebuddies#498]
**Do you want to request a feature or report a bug?**
Bug.

**What is the current behavior?**
Link leads to 404 Page Not Found. https://github.com/codebuddiesdotorg/codebuddies/tree/adding-contributor

**What is the expected behavior?**
Not sure. Are we still using this concept or no?
adding-contributor branch does not even exist anymore. This may have been an old feature? Not sure as I am new.
Example:
```
###How do I add myself as a contributor? Make sure you have recently git pull from master before continuing.

Once you've submitted your PR, switch to the branch **adding-contributor**. Then, you can add yourself to both the README.md and on our About page. **Keeping a separate branch for adding yourself as a contributor will alleviate most merge conflicts.**

**Switch to contributor's branch**
git checkout **adding-contributor**
````

**Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)**
Mac OS Sierra 10.12.4, Google Chrome Browser. Should not affect this issue.

**Comment by lpatmo** [comment]
Oops, good find! That branch must've gotten accidentally deleted.

**Comment by lpatmo** [comment]
@grfraser Thanks for this report! https://github.com/codebuddiesdotorg/codebuddies/tree/adding-contributor now exists again (it was pretty easy to create it on the github repo, so I decided to just go ahead and do it.)
