### ISSUE TITLE
Load Hangout Should Open in New Tab to Keep codebuddies.org accessible.

### ISSUE THREAD

**Issue by grfraser** [codebuddiesdotorg/codebuddies#499]
**Do you want to request a feature or report a bug?**
Feature.
**What is the current behavior?**
Load Hangout on main home page loads in current window.
**What is the expected behavior?**
Load Hangout should open a new tab so that codebuddies.org remains open in the browser and still easily accessible.

**Comment by lpatmo** [comment]
There is now a link that opens up a new containing the Jitsi hangout that appears above the embedded hangout; I believe that it satisfies this feature request.
