### ISSUE TITLE
Include attendee names in 2-hour hangout start Slack reminder

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#505]
Currently, this is the message we see in the Slack alert in the #general channel on codebuddies.slack.com two hours before a scheduled hangout is set to start: 

> Reminder! collaboration hangout: *Work Through "Grade School"on exercism.io & List Comprehensions* scheduled by @username is set to start in *less than two hours!*

Let's add the usernames of the attendees so that they'll get a ping/reminder as well:

> Reminder! collaboration hangout: *Work Through "Grade School"on exercism.io & List Comprehensions* scheduled by @username with RSVPs from @username2, @username3 is set to start in *less than two hours!*

**Comment by morrme** [comment]
I'd like to learn how to do this.

**Comment by lpatmo** [comment]
@morrme This is a juicy bug; was tempted to work on this next myself. :)

Files to start looking at are server/slack/methods.js and server/cron_job/methods.js, I believe.

**Comment by morrme** [comment]
@lpatmo looks like it! we can probably work on it together 👥

**Comment by sergeant-q** [comment]
I wrote the original code 🙂 so let me know if you need any help @morrme!

**Comment by morrme** [comment]
@sergeant-q @lpatmo it seems like [this line](https://github.com/codebuddiesdotorg/codebuddies/blob/release/server/slack/methods.js#L23) needs to be changed, pulling in each index of the ` hangout.attendees` array , right?

**Comment by sergeant-q** [comment]
@morrme that's right. Just make sure you still keep reference of the host!

**Comment by lpatmo** [comment]
@sergeant-q Any tips for getting reminder notifications to appear in #cb2-test? I changed the `hangout_reminder_interval` to `every 5 seconds` and have hangouts locally that start in a few minutes, but I'm not seeing anything in #cb2-test... 🤔

**Comment by sergeant-q** [comment]
@lpatmo let me take a look. Are you working off the latest `master` branch?

**Comment by sergeant-q** [comment]
@lpatmo I just tested it locally and it seems to be working just fine for me. See screenshot below (or checkout the #cb2-test channel!)

<img width="644" alt="screen shot 2017-05-17 at 9 07 04 am" src="https://cloud.githubusercontent.com/assets/1451729/26164055/5a26e6c6-3ae0-11e7-81fd-001626db25a0.png">

One thing to note. Make sure you set the **debug** flag to `true` in the /server/cron_job/methods.js` file! This will make the cron job run every minute to help with testing.

**Comment by lpatmo** [comment]
@sergeant-q Thanks for taking a look! The "a new teaching hangout has been scheduled" shows up fine, but the reminder notification (`Reminder! collaboration hangout: *Title of Hangout* scheduled by @hostname is set to start in *less than two hours!*`) does not.

**Comment by sergeant-q** [comment]
I see the issue. On hangout creation, there's a piece of code that is determining what to set the reminder fields to (either `true` or `false`) in the DB. Based on the current logic, if the hangout start time is less than or equal to 2 hours from now, then no need to send another reminder, thus it will set the

**day_reminder_sent:**
**hourly_reminder_sent:** 

both to `true`

The cron job only looks for active hangouts AND those whose reminder flags are set to `false`. In the case mentioned above, any hangout set to start less than two hours from the time it was created will always have that flag set to true, thus the cron job won't pick it up to send out the reminder.

I honestly cannot recall if this was intended or not but that's how it's working right now. I confirmed the logic by creating a hangout greater than two hours and both the new and reminder notification was triggered and send to the slack channel.

I do think we need to revisit this logic and decided on how we want it to behave.

**Comment by morrme** [comment]
is it possible to have a shorter reminder flag added?

**Comment by sergeant-q** [comment]
@morrme I think that's the discussion we need to have. I personally don't see any value in sending out a reminder for something less than two hours if a new notification was just sent out in the Slack channel. Otherwise, we'll get too spammy. 

I do, however, feel we should consider the current logic and get a consensus on what people want.

**Comment by morrme** [comment]
ah ok so the issue here is, if the hangout is scheduled within 2 hours of the start, only one notification is sent, and those cant ever have the attendees because this is the first notification.  so those hangouts are the only ones affected by this. how often do people schedule  that closely?   what would be the desired notification pattern for short notice hangouts? cc: @lpatmo

**Comment by lpatmo** [comment]
Thank you, @sergeant-q!! I'm an idiot and should've read the code more closely!

> if the hangout is scheduled within 2 hours of the start, only one notification is sent
I think that still makes sense... if a hangout is starting within two hours, people RSVPing to it will know it's starting soon, so probably won't need a reminder. The reminder is mostly necessary for people who've RSVPed to hangouts a day or more in advance and are likely to forget they RSVPed.

Maybe in the future we can consider an email notification to attendees 60 minutes before a hangout starts? (In addition to the 24-hour email notification.) Just an idea; this would be its own bug.

**Comment by sergeant-q** [comment]
@lpatmo I think people will read their email before they go into Slack to check. Which is why I like the idea of adding the attendees to the Slack but adding the email reminder is a great idea.
