### ISSUE TITLE
Remove text-align: justify on hangout posts and turn post titles black?

### ISSUE THREAD

**Issue by ISPOL** [codebuddiesdotorg/codebuddies#508]
Like this:
![screen shot 2017-05-06 at 10 18 48 pm](https://cloud.githubusercontent.com/assets/4441258/25777405/346977fc-32aa-11e7-954d-6355c6668552.jpg)

**Comment by lpatmo** [comment]
@dmost1 has submitted a PR/effectively claimed this issue.
