### ISSUE TITLE
Rename the #general channel to be called #announcements

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#512]
When this change is made in the CodeBuddies Slack, `"slack_alert_channel": "#general",` in the settings-production.json file on the prod repository will also need to be changed.

**Comment by morrme** [comment]
Should this be scheduled to happen at a certain time? Who has rights to make the slack channel name changes?

**Comment by lpatmo** [comment]
@morrme All the core contributors on https://codebuddies.org/about have the rights, but if we make the #general name before changing the settings-production.json file in prod the Slack alert notifications will break. Haven't decided when the time would be yet! Maybe sometime tonight...

**Comment by lpatmo** [comment]
I probably should've clarified there'll still be a #general channel; there'll just be a new #announcements channel as well, since it was widely requested!
