### ISSUE TITLE
Update Button Issue Screen Width: ~1000-1140px

### ISSUE THREAD

**Issue by grfraser** [codebuddiesdotorg/codebuddies#517]
Do you want to request a feature or report a bug?
**Bug**
What is the current behavior?
**Screwed up**
What is the expected behavior?
**Nice and neat**
Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)
**All most likely although I am using Chrome**

**Comment by grfraser** [comment]
<img width="1121" alt="screen shot 2017-05-28 at 2 26 56 pm" src="https://cloud.githubusercontent.com/assets/27697439/26531617/0b3f7174-43b2-11e7-9755-ce299f1d81f1.png">
<img width="355" alt="screen shot 2017-05-28 at 2 27 04 pm" src="https://cloud.githubusercontent.com/assets/27697439/26531619/0d780b5e-43b2-11e7-9ce9-1b339c942676.png">

**Comment by wuworkshop** [comment]
Just to add that this is also happening in Firefox 53 on Mac OSX, so this most likely happening in all browsers.

**Comment by lpatmo** [comment]
Thanks for looking, @wuworkshop!

**Comment by akosasante** [comment]
I'd like to take a look at this today if no one is already working on it?

**Comment by lpatmo** [comment]
@akosasante Go for it!

**Comment by stain88** [comment]
Can i be picky and ask for a re-open? Looking at this on stage at a width of 992-1016px, the "I'm working on..." and "Today I learned..." tabs have a different height: 
<img width="170" alt="screen shot 2017-06-30 at 14 39 21" src="https://user-images.githubusercontent.com/8461452/27738098-5a81f978-5da2-11e7-831a-7979f6a66b7b.png">

When "Today I learned..." is active, this is from 992-1037px. A similar thing happens on an iPhone 5-size device.

**Comment by akosasante** [comment]
Looks like "I'm working on" is one character longer, and gets pushed to a second line; can we just remove the space between "on" and the ellipses? Or is that too fragile/not proper fix?

**Comment by stain88** [comment]
That doesn't work if "Today I learned …" is active, I'm afraid

**Comment by akosasante** [comment]
Ah, right I see. 

We could do some combination of reducing the left/right padding in those tabs and/or reducing the font-weight of the active tab.

(Can I reopen this to make a fix [if so, how?], or do I just make a new PR pointing to this same Issue #?)

**Comment by stain88** [comment]
Just reducing the left/right padding is good enough, in my opinion. Not sure about protocol for reopening after a merge, so I'd wait for @lpatmo to answer that.

**Comment by lpatmo** [comment]
Thanks for noticing and flagging, @stain88. 

@akosasante A new PR pointing to this same issue would be great, if you're up for it.

**Comment by akosasante** [comment]
Do we generally prefer to keep things on a px basis, or would it make sense to use rem units here?

**Comment by lpatmo** [comment]
`rem` is fine. (We should probably switch over `px` to `em` `rem` in general, but that's a later bug.)
