### ISSUE TITLE
Organize a better Table of Contents structure for new CodeBuddies Contributor/Developer Docs

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#524]
Major kudos to @distalx for suggesting that we should have a separate repository to hold our docs, and for suggesting using gitbook.

Here's our Gitbook (soon to be located at docs.codebuddies.org once DNS records refresh): https://codebuddiesdotorg.gitbooks.io/documentation/content/

As you can see, it's very reader-friendly (and definitely a lot more reader-friendly than scrolling through a `.md` page).

![screen shot 2017-06-24 at 12 59 29 am](https://user-images.githubusercontent.com/4512699/27506906-71be0520-5878-11e7-925c-5989b051885f.jpg)

Note: the repo that hosts the new documentation is at https://github.com/codebuddiesdotorg/documentation

**Comment by wuworkshop** [comment]
@lpatmo uh, shouldn't this issue be part of the documentation repo? 😅

**Comment by lpatmo** [comment]
Heh, yes! Thanks @wuworkshop, and am going to close this since docs.codebuddies.org now has a better outline/structure.
