### ISSUE TITLE
Give users ability to log in using Google too instead of relying on Slack?

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#53]
Some thoughts from users in a hangout: 
- We should use Google login. 'Cause Slack login takes two steps and also when you want to join hangout you also need login to your google account.

Downside:
- no easy way to DM a user via Slack

Upside:
- Users need to log in using google anyway to access Google Hangouts
- Asking everyone to sign up on Slack and THEN login via this app is two steps.

**Comment by adachiu** [comment]
Google login would be a good idea since convenience to access a Google Hangout is arguably more important than DM-ing a user.
