### ISSUE TITLE
Add a link to medium.com/codebuddies on the footer

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#541]
Below "FAQ", let's add a link to our Medium publication at medium.com/codebuddies.

![screen shot 2017-07-23 at 12 08 02 pm](https://user-images.githubusercontent.com/4512699/28502090-a7e2a56e-6f9f-11e7-9cb7-31bb89997542.jpg)

**Comment by valishah** [comment]
Hi @lpatmo, I'm a first time contributor . Would love to be part of the community . Can you help me to understand the requirement. If i'm not wrong we should be having one more label that says Medium and should be redirecting to medium publication ? Am i correct ?

**Comment by lpatmo** [comment]
@valishah Yes, you were right! Sorry I didn't make the issue clearer. (I added the word "Publication" to it, but that was it.)

We're actually working on docs.codebuddies.org -- which is unfinished so it's not live on our README.md yet, but feel free to take a look, and let me know if you have any questions! Also: have you joined the CodeBuddies Slack? You can stay up to date on project status or ask questions in the #codebuddies-meta channel there. :)
