### ISSUE TITLE
[Beginners] Add link to Open Collective in footer

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#546]
Let's add a link to our Open Collective (opencollective.com/codebuddies) below the "Medium Publication" link. 

![screen shot 2017-08-05 at 10 05 22 am](https://user-images.githubusercontent.com/4512699/28997299-d58647c0-79c5-11e7-92f6-a3ec58736b60.jpg)

**Comment by alesfer001** [comment]
WIP
