### ISSUE TITLE
Email notifications: send email reminders with Sparkpost

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#552]
- Send a reminder email after a user RSVPs to a hangout, 24 hours before the hangout starts
- Send a reminder email after a user RSVPs to a hangout, 2 hours before the hangout starts
- Send a followup email to attendees of a hangout after the hangout ends, to remind them to share what they learned

//Reminders
SUBJECT: Reminder: {{ hangout_topic }}

The hangout titled: <strong><a href="{{hangout_url}}"> {{hangout_topic}}</a></strong>, is set to start within [24]/[2] hours, at <strong>{{hangout_start_time}}</strong>. This hangout was scheduled by <a href="https://codebuddies.slack.com/messages/@{{host}}">@{{host}}</a>.<br>
<br> <strong>Please update your RSVP if you can't make the hangout anymore. We hope to see you there!</strong>

---
//Followup
SUBJECT: How was "{{ hangout_topic }}"?

Please share what you learned at <strong><a href="{{hangout_url}}">{{hangout_topic}}</a></strong>. Thank you!

**Comment by sergeant-q** [comment]
Why are we moving away from mailgun?

**Comment by lpatmo** [comment]
Mailgun was failing to send emails at all because I couldn't get the DNS settings to verify. I wanted to use Sparkpost mostly because I wanted to get more familiar with it -- and actually also couldn't get the DNS settings to verify at first, but finally was able to verify it by sending an email to a codebuddies.org email domain. 

Other than that, I don't have a *terribly* good reason for moving away from Mailgun (other than the annoying verification problem) except that Sendgrid/Sparkpost seemed to have better reputations.

**Comment by sergeant-q** [comment]
Good deal. Sparkpost seems developer friendly.

**Comment by lpatmo** [comment]
See: https://github.com/codebuddiesdotorg/codebuddies/pull/555
