### ISSUE TITLE
STUDY GROUPS: more descriptive error message for required tagline

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#565]
Suggested by @tonypnode: 

> When trying to add a new study group I didn't put in a tag line. The only indication of the error was a flash message that said "Study Group Name". You could put a more detailed error notifying the user that a tag line is required. Or place a "required" indicator next to the Tag field.

**Comment by tonypnode** [comment]
Looks good!

A minor thing...The flash message pops up behind the "add new study group" dialog. Not sure if you can change the zed of that message.

<img width="861" alt="screen shot 2017-09-10 at 5 18 20 pm" src="https://user-images.githubusercontent.com/20878906/30253117-a412dff2-964c-11e7-8730-ce633ce34152.png">
