### ISSUE TITLE
Show form error messages inside modal, not outside of it

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#568]
Good feedback from @osanseviero:

![image](https://user-images.githubusercontent.com/4512699/30253161-5a137622-9634-11e7-93c0-217cf38da3c1.png)

For good user experience, try to contain things were they belong. Here the website is giving feedback on the form outside the modal, which seems a bit messy. This could potentially cause a11y issues as well.

**Comment by agatac** [comment]
Hi, I can have a look if nobody claimed this issue!
