### ISSUE TITLE
STUDY GROUP: Change redirect on study group "hang up"

### ISSUE THREAD

**Issue by tonypnode** [codebuddiesdotorg/codebuddies#576]
Clicking the "Hangup" button in the Jitsi study group redirects the user to https://meet.jit.si/.

If possible, it would be nice if it redirected back to the study group page.

**Comment by lpatmo** [comment]
@tonypnode Thanks for filing! You mean redirect back to /study-groups, right?

According to https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md, I think the event listener we want is `readyToClose`. Will look into this.

**Comment by lpatmo** [comment]
Ok, turns out it wasn't too difficult to do the redirect. Code is client/templates/hangout/hangout-frame.js, and will submit a PR:

```
+    instance.api.on('readyToClose', () => {
+      Bert.alert({
+          type: 'success',
+          message: 'Thanks for joining the hangout!',
+          hideDelay: 3500
+        });
+      FlowRouter.go('all study groups');
+    });
```
Thanks again for the suggestion!
