### ISSUE TITLE
Study Groups: Members Tab and Easier Member Mgmt

### ISSUE THREAD

**Issue by arturolei** [codebuddiesdotorg/codebuddies#582]
There should be an easier/more intuitive layout from the Members tab for adjusting member roles (e.g. admin or member). Take as a model, this shot from FB; clicking on the "modifica" button lets you instantly edit member roles.
![screen shot 2017-09-10 at 6 30 06 pm](https://user-images.githubusercontent.com/4889231/30255900-97e77cce-965b-11e7-83b0-90ffe204a363.png)

**Comment by lpatmo** [comment]
Good suggestion, @arturolei!

Here is the old view:
![screen shot 2017-09-10 at 7 21 03 pm](https://user-images.githubusercontent.com/4512699/30256133-40a88910-965d-11e7-8d89-b262a02b12b1.jpg)
