### ISSUE TITLE
STUDY GROUPS: Messy study groups dashboard

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#584]
<img width="1001" alt="screen shot 2017-09-10 at 21 30 28" src="https://user-images.githubusercontent.com/7246357/30258580-71da4e76-966f-11e7-895c-1c1f6eebe497.png">

Elements should have the same height, and new elements should go to the left.

**Comment by osanseviero** [comment]
<img width="963" alt="screen shot 2017-09-10 at 21 36 25" src="https://user-images.githubusercontent.com/7246357/30258649-263055b4-9670-11e7-9fe2-6ec6b972c014.png">

**Comment by schoettkr** [comment]
I'm working on this!
