### ISSUE TITLE
STUDY GROUPS: Don't allow to create a study group with the same name

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#585]
Self explanatory. I was able to create two study groups with the same name.

**Comment by railsstudent** [comment]
Hi, I would like to work on this issue. Thanks.

**Comment by distalx** [comment]
I think instead of making it mandatory to have unique names, we should encourage users to not use generic names for GROUPS by creating some sort of community guidelines about it.

**Comment by distalx** [comment]
@railsstudent, It's all yours. I've updated the label to `claimed`.

**Comment by railsstudent** [comment]
I will check for unique name and throw error if the name is already used.
