### ISSUE TITLE
STUDY GROUPS: Creating more study groups

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#587]
When I didn't have any study group, I was able to create many without the button disappearing. After changing screens, I'm not able to create a new study group. 

There are two possibilities here as I see
- Be sure that the button appears always.
- Remove the button after creating a study group.

I prefer the first option. What do you think?

**Comment by lpatmo** [comment]
Makes sense! There should always be a button on the "my study groups" page. Otherwise, it's not entirely clear that to start a new group you'd have to click on the "+" sign on the nav.

**Comment by lpatmo** [comment]
I will work on this issue.

**Comment by osanseviero** [comment]
Could we have this button in /my-study-groups as well?
