### ISSUE TITLE
STUDY GROUPS: Really long name of study group or description

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#589]
First of all, I think there should be a char limit in the description just like there is a limit in the learnings. Second of all, the divs should manage better long titles-descriptions, specially for the dashboard screen.

<img width="925" alt="screen shot 2017-09-10 at 22 15 52" src="https://user-images.githubusercontent.com/7246357/30259361-cd7e9984-9675-11e7-910f-cb51de66d8e0.png">
<img width="300" alt="screen shot 2017-09-10 at 22 16 02" src="https://user-images.githubusercontent.com/7246357/30259360-cd7e817e-9675-11e7-809f-5b7928001a8d.png">

**Comment by osanseviero** [comment]
<img width="1113" alt="screen shot 2017-09-10 at 22 28 57" src="https://user-images.githubusercontent.com/7246357/30259677-760cd862-9677-11e7-8353-75e2d8120f2f.png">

**Comment by arturolei** [comment]
I'm going to work on this.
