### ISSUE TITLE
STUDY GROUPS: End page row width

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#590]
I don't know if it was designed to look like it, but, in large screen, I don't like too much that the widths are different. This is a matter of taste, it really depends of what you think.

Here are the two options in small and big screens.

<img width="609" alt="screen shot 2017-09-10 at 22 17 58" src="https://user-images.githubusercontent.com/7246357/30259419-204be1ee-9676-11e7-9a0f-02ca478de091.png">
<img width="926" alt="screen shot 2017-09-10 at 22 18 33" src="https://user-images.githubusercontent.com/7246357/30259420-204c0084-9676-11e7-99de-6c924c85f5c5.png">

VERSUS
<img width="631" alt="screen shot 2017-09-10 at 22 20 26" src="https://user-images.githubusercontent.com/7246357/30259459-48684032-9676-11e7-9143-cc7b8255cc28.png">
<img width="1006" alt="screen shot 2017-09-10 at 22 20 30" src="https://user-images.githubusercontent.com/7246357/30259460-486a0ea8-9676-11e7-94c8-a5cfb35ee1c6.png">

**Comment by lpatmo** [comment]
Agreed -- bottom row should be same width.

**Comment by dantesolis** [comment]
I would go ahead and begin with this one before tackling my other PR as to get reacquainted with the project. If that's ok with you guys. :)

**Comment by lpatmo** [comment]
@dantesolis I've marked this issue as claimed for you. :) Let us know if you have any questions!

**Comment by dantesolis** [comment]
Hey guys, just FYI I finished the changes, committed the changes on my fork, now trying to figure out how to create the PR for `upstream`, but you can already see the changes [here](https://github.com/dantesolis/cb-v2-scratch/commit/7cdb56574d4f04e6a0c71fe62a99444c5e503186).

**Comment by lpatmo** [comment]
Thanks @dantesolis! I believe if you go to https://github.com/codebuddiesdotorg/codebuddies, you should see a green button that asks if you'd like to submit a PR. 

One question, from looking at the diff: why did you remove all the underscores from the imports of the SCSS files in client/css/style.css?

**Comment by stain88** [comment]
To be fair, import statements need neither underscores, nor '.scss' at the end: it's magic

**Comment by lpatmo** [comment]
Oh my god, mind blown! @stain88 You're right; the imports work looking like ```@import 'colors';
@import 'base';``` even though the filenames themselves look like _colors.scss and _base.scss!

**Comment by stain88** [comment]
If there's one thing I know, it's how to be lazy and type less...
And just to clarify, "no underscores" means no leading underscores: the ones in the middle of a file name need to stay.

**Comment by dantesolis** [comment]
I'll go ahead and remove the `.scss`  from the import statement. Thanks @stain88, good eye had forgotten about that.
