### ISSUE TITLE
STUDY GROUPS: Bug in char count for learnings

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#591]
2 bugs in one bundle.

Let's see, first of all, the bug count is the same for both text areas in the learnings site.
<img width="989" alt="screen shot 2017-09-10 at 22 30 14" src="https://user-images.githubusercontent.com/7246357/30259717-be4ead62-9677-11e7-97d2-0b69d21aaff1.png">
If I change the one in the left, the one in the right changes. If I change the one in the right, none change. I think that the text area is wrongly linked.

If you just write in the area, and hit enter, it fails:
<img width="1038" alt="screen shot 2017-09-10 at 22 30 01" src="https://user-images.githubusercontent.com/7246357/30259735-dbd1b096-9677-11e7-8ef6-34e000d8a3c8.png">
<img width="1059" alt="screen shot 2017-09-10 at 22 30 06" src="https://user-images.githubusercontent.com/7246357/30259734-dbbe7d82-9677-11e7-8e5b-2bbf7c1aa206.png">

It's trying to submit the text from the left, which is empty.

**Comment by osanseviero** [comment]
Probably related to this as well, when I'm in the one in the left, and I hit *space*, the focus jumps to the one in the right.
<img width="1049" alt="screen shot 2017-09-10 at 22 36 32" src="https://user-images.githubusercontent.com/7246357/30259857-94ea9e62-9678-11e7-9ecd-594c79493496.png">
<img width="1003" alt="screen shot 2017-09-10 at 22 36 35" src="https://user-images.githubusercontent.com/7246357/30259856-94ea91a6-9678-11e7-9f00-d90b2f39e568.png">

**Comment by distalx** [comment]
I believe if we remove learning box form the left side bar that will resolve this issue.

**Comment by lpatmo** [comment]
Ha, was just going to say that!

I'm a little partial to the idea of keeping the learnings box on the sidebar so that people can share learnings no matter what tab they're in, but at the very least we definitely shouldn't have two learnings boxes appear when a user is on the "learnings" tab.

**Comment by osanseviero** [comment]
Mmm I don't know. Removing the learning box just in one tab might make the experience inconsistent...I'm not sure that's the best way to fix this. Note: removing it actually fixes the bug. It might be a good way, though. 

<img width="1005" alt="screen shot 2017-09-11 at 20 32 10" src="https://user-images.githubusercontent.com/7246357/30307045-779c91ae-9730-11e7-8d0e-8a83e26b3577.png">
<img width="1040" alt="screen shot 2017-09-11 at 20 33 06" src="https://user-images.githubusercontent.com/7246357/30307046-779f62d0-9730-11e7-8cb4-eac604ad4382.png">
<img width="978" alt="screen shot 2017-09-11 at 20 33 12" src="https://user-images.githubusercontent.com/7246357/30307047-779ff4fc-9730-11e7-8c4f-4d0701ce1840.png">

**Comment by lpatmo** [comment]
After thinking about it a bit more, I think we can remove it from the sidebar, so that it'll only show up on the "Learnings" tab.

Question: what do you guys think about renaming "Learnings" to something like "Progress Log"? Do you think it would inspire more people to write about what they learned?

**Comment by lpatmo** [comment]
I will take on this issue.
