### ISSUE TITLE
STUDY GROUPS: Let owners transfer ownership of study group to another user

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#592]
Not sure if this should be a button in the "settings" tab, or if owners should automatically be able to assign "owner" in the members' tab when they click to modify the permissions of other users.

Thoughts?

**Comment by lpatmo** [comment]
... and I assume there can be only one owner of a study group, but multiple admins and moderators.

**Comment by railsstudent** [comment]
It should be a button in Settings tab. At least, the owner is intended to transfer ownership to somebody else and leave the study group.
Doing it in member can lead to false transfer because owner makes an error when changing status of member in members tab.
