### ISSUE TITLE
Give each group its own "status" area

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#597]
When I open up a study group page, it would be nice to see:
- who else is online
- a place to type in my current static status within the study group (e.g. "just starting out with this tutorial", or "on Ch. 5" or "interested in pairing")

This should go in the sidebar.

**Comment by railsstudent** [comment]
@lpatmo Just some questions for this issue:
1) All these in the sidebar below Organizers?
2) Can other member see my current static status?
3) When I type current status, does it replace the previous status?

**Comment by lpatmo** [comment]
> All these in the sidebar below Organizers?
Yep!

> Can other member see my current static status?
Yep! Was thinking this feature would be useful if the group were MOOC-focused or book-focused (i.e. there is a linear progression of materials). Even if it's not, the status area could be used for members to state that they're a beginner in the topic, or intermediate in the topic, etc.

> When I type current status, does it replace the previous status?
I think so. I don't think we'd need to remember the previous status, since that history could be archived in the Progress Log.

**Comment by railsstudent** [comment]
@lpatmo I think I can do the show who else is online part. 
I am still not clear about the current status part. If the group has a lot of members and their status are all listed on the sidebar, the sidebar can grow very long. 
I am not too sure about it.

**Comment by lpatmo** [comment]
@railsstudent Good point! Perhaps if we gave the content area a `max-height: 400px` or something and made it scrollable, that would help.

**Comment by railsstudent** [comment]
@lpatmo Some questions on database modelling.
1. Where is the MongoDB collection schema defined?  I look at server folder and do not see any database script. I only see MongoDB collection creation in server/app.js
2. If a member joins two study groups, A and B, does member object in collection A different than member object in collection B? If yes, adding current status is simply adding a new property in member object. Otherwise,  some kind of data mapping is required.

**Comment by lpatmo** [comment]
> Where is the MongoDB collection schema defined? I look at server folder and do not see any database script. I only see MongoDB collection creation in server/app.js

Do you know about the control-m trick from the mongol package? (https://docs.codebuddies.org/walkthroughs/tips.html) That's an easy way to look at how the schema is structured. Otherwise, you can see the schema when we insert the data into a collection -- for examples, in `hangouts/methods.js`. 

> If yes, adding current status is simply adding a new property in member object. 

Yes, exactly! e.g.:
```
  "members": [
    {
      "id": "5qocx2ZpKf9nrap3H",
      "name": "codebuddies",
      "avatar": "https://avatars.slack-edge.com/2017-07-11/210945910657_1e4c9780f852d27b2018_72.jpg",
      "role": "owner",
+   "status": "on Ch. 2"
    }
  ],
```

**Comment by railsstudent** [comment]
@lpatmo  I want to claim this item after having bigger understanding than before.
However, I propose to show status and status input box in members tab, similar to Learning

**Comment by lpatmo** [comment]
@railsstudent Oh, that's a brilliant proposal! I did a quick mockup in the browser of what it might look like. Were you thinking of something like this?

![screen shot 2017-10-06 at 8 00 13 pm](https://user-images.githubusercontent.com/4512699/31304173-2888bdcc-aad1-11e7-9833-fe4430d5e484.jpg)

**Comment by distalx** [comment]
Mockup looks good. we could also include a `timestamp` field in the schema so we can list members by their recent activity.

**Comment by lpatmo** [comment]
Good point, re: including a timestamp!

**Comment by railsstudent** [comment]
@distalx @lpatmo  I will work on it. My CSS is not that great, so i will take longer to complete

**Comment by lpatmo** [comment]
@railsstudent I'm happy to help with the CSS. :) Feel free to ping me @linda on Slack.

**Comment by railsstudent** [comment]
@lpatmo @distalx  Please add the claim tag and I can start as early as tomorrow.  thanks.

**Comment by distalx** [comment]
cool, let me know if you need any help :)
