### ISSUE TITLE
STUDY GROUPS: 'Scheduler' tab

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#599]
@distalx created a demo of a scheduler that could be helpful for study groups, that'll let users see what days (and times) other people are free, and the overlap between users.

Feel free to play around with the demo here:
https://tan-wombat.herokuapp.com/jam/QPt5tYoTJAawznEEo

![screen shot 2017-09-13 at 9 52 49 pm](https://user-images.githubusercontent.com/4512699/30412739-619346d8-98ce-11e7-9c43-107cbecb04dc.jpg)

A user would:
- select a day and a length of time in their own timezone (e.g. 8-9pm EST) and click "set"
- That length of time would appear as a chunk on the graph, and overlap with other users' times. Everyone's times will be automatically converted on the backend. 
- TODO: Display on the graph the particular day that we're looking at, maybe as tabs. 

Feedback welcome! Would you find this tool useful to schedule times that other people in a study group are available? What do you think about the design that could be improved?

**Comment by bengineerdavis** [comment]
I noticed this feature isn't implemented within Study Groups at the moment. If someone could look into this, that would be greatly appreciated!

My system:
Fedora 30. Chrome.
![cb_group_'YOUR AVAILABILITY'](https://user-images.githubusercontent.com/52514382/61986641-9b9f0000-afde-11e9-93fa-baf3856b3b0a.png)
