### ISSUE TITLE
STUDY GROUPS: Margin of owner/member box. 

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#603]
This should be easy for beginners. It's just adding few pixels of margin to the member/owner box at the top.

Current
<img width="326" alt="screen shot 2017-09-17 at 20 34 12" src="https://user-images.githubusercontent.com/7246357/30528422-baa2b148-9be7-11e7-9a63-456b9ed63358.png">
<img width="327" alt="screen shot 2017-09-17 at 20 34 30" src="https://user-images.githubusercontent.com/7246357/30528421-baa272f0-9be7-11e7-89f5-9401e1bba197.png">

Proposed - 5 pixels margin top
<img width="324" alt="screen shot 2017-09-17 at 20 33 40" src="https://user-images.githubusercontent.com/7246357/30528430-c549dcc0-9be7-11e7-8762-53f9773856ae.png">
<img width="328" alt="screen shot 2017-09-17 at 20 34 05" src="https://user-images.githubusercontent.com/7246357/30528429-c549d8b0-9be7-11e7-9414-fc4a0fa05882.png">

**Comment by dantesolis** [comment]
@osanseviero, @lpatmo, may I take this one? Thanks

**Comment by lpatmo** [comment]
@dantesolis Go ahead, thanks!
