### ISSUE TITLE
PTT deck for new contributors

### ISSUE THREAD

**Issue by osanseviero** [codebuddiesdotorg/codebuddies#608]
We're working on a presentation with the idea of making it easier to start contributing the project and have a better sense of how everything works. Any feedback is welcome. 

https://docs.google.com/presentation/d/1tlU9hWUsP44W6I0qEre0CgqrjLUaK1Vwr-hGq7phn0Q/edit?usp=sharing

**Comment by lpatmo** [comment]
A link to this PPT has been added to docs.codebuddies.org. :)
