### ISSUE TITLE
Update homepage :)

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#619]
Problems with the home page right now:
- no mention of "open source" or our Github repo
- no mention of study groups
- Animated gif is outdated
- Explain how Jitsi is an open-sourced version of Google Hangouts, and the first time you join, you'll need to download a browser extension. Also: works best in Chrome or Firefox.

**Comment by angelocordon** [comment]
@lpatmo are you looking to revamp the front page or just update some of these issues?

**Comment by lpatmo** [comment]
@angelocordon I'm planning to sit down tonight or tomorrow night and revamp the home page entirely, at least content-wise. The animated gif (maybe 30-second video?) will take a bit of time (some volunteers + a scheduled hangout) to make.

**Comment by alfougy** [comment]
I’ll see if I can peep my head in. I haven’t made any pull requests yet.

**Comment by lpatmo** [comment]
Here is a short/quick update of the content on the homepage... feedback welcome! (I might open up another issue for the homepage, since the animated gif and various screenshots are outdated, so ideally we'd add updated screenshots and explain the features within study groups better.)

![homepage_redesign_1_oct19](https://user-images.githubusercontent.com/4512699/31762469-242550a8-b470-11e7-96c5-4f106dff7e38.png)
