### ISSUE TITLE
Contributing Workflow Update Recommendations - Pull Requests (PRs) & Branch Naming

### ISSUE THREAD

**Issue by sergeant-q** [codebuddiesdotorg/codebuddies#62]
## Pull Requests

I am suggesting we move to having contributors submit pull requests for new features/issues.  Considering we are working in a **shared repository model**, this workflow is aligned with best practices for contributing to open-source projects which offer the following key benefits:
- Notification to project maintainer of new code changes submitted
- Code Review (can view the actual diffs)
- Pull Request discussions (comments, additional commits, file and line notes)
- Traceability
- Keeps branch list to a minimal (ideally only two branches should ever exist permanently `master` and `staging`)

Our current contributing guideline is keeping closed/completed branches on the repo and are not being deleted after the changes have been merged into the **master** branch. By following the new pull request workflow, we can have the contributor (or even the project maintainer) safely delete the branch once the PR has been accepted and the code merged back into master. 
## Branch Naming Convention

To keep things rather simple, we are suggesting we follow a basic naming convention when creating a new branch as follows:

**`issue-#`** or **`feature-#`**

For any new **feature** or **issue** a new one **must** be created against the project's repo. A number will be issued for it.  Use that number to identify the branch.  Below is an example:

**git command to create a new branch**
  `git checkout -b <branch-name>`

**suggested naming example**
  `git checkout -b issue-7` or `git checkout -b feature-23`
## Resources

Pull Request [tutorial](https://yangsu.github.io/pull-request-tutorial/) 
How to pull request on github [tutorial](https://help.github.com/articles/using-pull-requests/#article-platform-nav)

**Comment by lpatmo** [comment]
Whoa, just noticed Github now let us use emoticons to respond to issue posts! That's great!

Looks like four active people here endorse, so let's go with it. 

To recap:

*We're going to do everything we did before (including creating a new branch, etc.) but *before* merging into master, create a new pull request for our commit so that we take advantage of Github's features for pull requests.*

**Comment by distalx** [comment]
This blog is really intreating, it's regarding thoughtful git practises.
https://robots.thoughtbot.com/better-commit-messages-with-a-gitmessage-template

I believe we should also consider having a some sort of **_template_** for commit messages.

**Comment by sergeant-q** [comment]
Not a bad idea and good habit to get into.

**Comment by wuworkshop** [comment]
I just realized we weren't taking advantage of some of GitHub and Waffle.io's keywords that provide some nice automation to a project's workflow (like automatically closing issues after a PR is merged). After cbv2 is launched, might want to to tweak the naming convention to follow Waffle's recommended workflow here: 

https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking

**Comment by sergeant-q** [comment]
@lpatmo @distalx @wuworkshop I think it's fair to say these new guidelines are now being followed? Can we close this issue?

**Comment by distalx** [comment]
Would it make sense to  add [commitizen](https://commitizen.github.io/cz-cli/) into workflow ?

**Comment by distalx** [comment]
Enforce contribution guidelines for PRs, commits, branch names and issues using http://gitmagic.io   !!!
