### ISSUE TITLE
Make sidebar of study group hideable

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#628]
On a hangout page right now, you click on the "x" icon on the sidebar to hide it:
https://codebuddies.org/hangout/bJweLDir2BkT86rtE#

This slides the sidebar to the left and makes the hangout frame full width.

We should similarly make the sidebar on a study group hideable as well:

https://codebuddies.org/study-group/pystudy/H9qgqC7JZAro5RjsW

Relevant inspiration:
`client/templates/hangout/hangout.js`
```
32-Template.hangout.events({
33:  'click #hide-sidebar': function() {
34-      $('.hangout-sidebar').hide();
35-      $('.hangout-body').removeClass('col-md-9').addClass('col-md-10 col-md-offset-1');
36-      $('#show-sidebar').fadeIn();
37-  },
38-  'click #show-sidebar': function() {
39-      $('.hangout-sidebar').show();
40-      $('.hangout-body').removeClass('col-md-10 col-md-offset-1').addClass('col-md-9');
41-      $('#show-sidebar').hide();
42-  },
```

**Comment by lpatmo** [comment]
If anyone would like to work on this issue together, let me know.

**Comment by kodinglife** [comment]
I'm on it!

**Comment by lpatmo** [comment]
@kodinglife Let me know if you have any questions! We're also in the CodeBuddies #codebuddies-meta channel on Slack.

**Comment by 2hands10fingers** [comment]
$(".clickedItem").click(function() {
  $(".well").toggle("bye");
});

.bye {
  display: none;
}


.clickedItem can be an added x. Where would I make the pull request to?
