### ISSUE TITLE
STUDY GROUPS:  Duplicating a Scheduled Hangout for a Study Group Removes the Study Group Affiliation

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/codebuddies#631]
Currently, when you create a Hangout on Codebuddies.org, you are asked to assign the Hangout to a Study Group (either Codebuddies Default, or another group you administer via drop-down).  The Hangout is then labeled with the name of the study group.

However, when you _duplicate_ a Hangout, the Study Group flag is not copied over, and the drop-down in the creation window only has CodeBuddies Default as an option.

Since the Study Group assigned to  a Hangout is not editable after that Hangout is created, this is a little bit frustrating for Study Group Admins:  They either have to re-create a Hangout from scratch, or they have subsequent Hangouts in a series listed as Default Codebuddies hangouts not associated with their Study Group.

We should either copy over the Study Group affiliation if a Hangout is copied, or allow the affiliated Study Group to be assigned/edited after a Hangout has been created.

**Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)**
_Tried Chrome, Safari, and FireFox....all have the same issue, so I don't think it's display/browser related._

**Study Group Affiliated Hangout Window after Pressing "Duplicate":**
![screen shot 2017-10-01 at 12 58 32 pm](https://user-images.githubusercontent.com/5923094/31058437-5220672a-a6a8-11e7-8d6b-470d9ede79a0.png)

**Duplicated Hangout Window after Pressing "Edit":**
![screen shot 2017-10-01 at 12 58 52 pm](https://user-images.githubusercontent.com/5923094/31058451-86e41d26-a6a8-11e7-88da-324124eafc30.png)

**Comment by lpatmo** [comment]
@distalx has a PR for the first issue in #631. 

Let's talk about the second issue (ability to edit the group for a hangout) in a separate issue! It's a bit complicated because of notifications.
