### ISSUE TITLE
Move "Learnings" box from the study group sidebar over to the "Progress Log" tab

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#637]
Right now the "learnings" box is on the sidebar of a study group:
![screen shot 2017-10-04 at 1 29 52 am](https://user-images.githubusercontent.com/4512699/31166449-a43c9888-a8a3-11e7-8c24-a84f5e909f58.jpg)

Let's move it over to the "Progress Log" box:
![screen shot 2017-10-04 at 1 30 18 am](https://user-images.githubusercontent.com/4512699/31166480-bb65d70e-a8a3-11e7-92cf-9ca225c237b1.jpg)

If you're new to the codebase, please check out docs.codebuddies.org for steps on how to fork the project and get started. You might also find https://docs.google.com/presentation/d/1tlU9hWUsP44W6I0qEre0CgqrjLUaK1Vwr-hGq7phn0Q/edit?usp=sharing helpful.

This is a `good-for-beginners` issue. 

Clues to solving:
```
            {{#if isInRole 'owner, admin, moderator, member ' _id}}
              {{> hangoutLearned }}
            {{/if}}
``` 
from `single_study_group.html`

Move this to the HTML file containing the `studyGroupLearnings` template.

IMPORTANT: If you want to work on this issue, please leave a comment to claim it before you submit a PR.

**Comment by W01fw00d** [comment]
Hi! I would like to work on this issue :)

**Comment by distalx** [comment]
@W01fw00d Great. I've updated the label to `claimed`.

**Comment by W01fw00d** [comment]
![codebuddies_learnings](https://user-images.githubusercontent.com/18144822/31183149-09fbcffe-a926-11e7-8cd7-81fda17c58bf.PNG)

How does it look? Any additional change needed?

**Comment by lpatmo** [comment]
@W01fw00d Looks great! Please submit a PR!
