### ISSUE TITLE
Bug: Changing the who-can-start-a-hangout-in-a-group permissions doesn't save

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#643]
As reported by @sabliao: changing the setting to have anybody be able to start a hangout seems to 'save' okay (I get the confirmation popup and confirm it), but when I refresh the page, it still shows only admins and moderators and start a hangout. 

I can confirm that I see this bug as well.

**Comment by sabliao** [comment]
Dang, that was fast. Nice one, @lpatmo! *I, instead, stayed up watching "Queen of Katwe" with my dad...

**Comment by sabliao** [comment]
I can see that the setting of 'everybody' [having permission to start a hangout] is saved.
![image](https://user-images.githubusercontent.com/4286238/31313239-2804118c-ab92-11e7-803b-c9ab618d4c5d.png)
But on the Members tab, I still see the text that says, "Only admins and moderators can schedule hangouts for this group."
![image](https://user-images.githubusercontent.com/4286238/31313247-47f7c36c-ab92-11e7-8b54-80e85ed785ff.png)

**Comment by lpatmo** [comment]
Aha, thanks for finding that @sabliao! :) The feature is fixed, but I forgot that we had that piece of text there for owners. Will change the text.
