### ISSUE TITLE
Consistent naming: 'organizer' vs. 'moderator'

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#650]
Right now, on the `members` tab, the creator/owner of a study group can click to turn a member into a `moderator` or an `admin`. 

The issue: if a member is turned into a `moderator`, their label on localhost:3000/study-groups turns into the label `Organizer` instead of `Moderator`. 

We should either change all the places where `Organizer` is listed into the word `Moderator`, or change all the places where `Moderator` is defined into `Organizer`. (Do you guys have a strong opinion re: which label sounds better?)

So the three permission roles could either be: 
- admin, organizer, and member 
OR
- admin, moderator, and member

If it helps, here are all the places where the term `Organizer` is used: 
```
client/templates/study_groups/all_study_groups_homepage.html
22:                    <span class="label-box label label-primary pull-right">Organizer</span>

client/templates/study_groups/all_study_groups.html
43:                    <span class="label label-primary pull-right">Organizer</span>

client/templates/study_groups/my_study_groups.html
30:                  <span class="label label-primary pull-right">Organizer</span>

client/templates/study_groups/study_group_search_result.html
22:                  <span class="label label-primary pull-right">Organizer</span>
```

**Comment by josephkmh** [comment]
I'd be happy to fix this one - I think `Moderator` is a better term than `Organizer`. Is that alright?

**Comment by stain88** [comment]
To me, "Organizer" sounds singular, while "Moderator" sounds plural (as in, you would only have 1 organizer in the group, but could easily have more than 1 moderator taking part).

So I vote for Moderator.

**Comment by lpatmo** [comment]
Thanks for weighing in, @josephkmh and @stain88! It'll be straightforward, then -- changing `Organizer` to `Moderator`. I will add the `claimed` label for you, @josephkmh. Thanks! Let me know if you have questions.
