### ISSUE TITLE
Re-organise nav layer by adding a "Community" header with new links

### ISSUE THREAD

**Issue by distalx** [codebuddiesdotorg/codebuddies#654]
Let's move the _About_ and _FAQ_ pages under a "Community" section.

Also, let's add a few more links to this section: Slack, Github and the Open Collective. 

Finally, let's add a link to our Medium publication under the name "Blog". 

Please see mockup below for reference!

<img width="206" alt="screen shot 2017-10-12 at 2 45 00 pm" src="https://user-images.githubusercontent.com/11193792/31489052-284045d4-af5d-11e7-8677-14fea30df41f.png">

**Comment by lpatmo** [comment]
A++!

Brilliant proposal. I've actually been wondering how we could better highlight our /faq, /about, Slack and other links without cluttering up the header nav. 

Some steps for whoever tackles this issue:
- Create the "Community" tab on the header nav
- Remove the "Github" and "Slack" links from the Profile tab and put it into this "Community" tab
- Add the other links as well

Links:
- /about
- https://codebuddies.slack.com
- https://github.com/codebuddiesdotorg/codebuddies
- https://medium.com/codebuddies
- /faq
- https://opencollective.com/codebuddies

If you're new to this project and need instructions about how to run the app, please check out docs.codebuddies.org or our helpful onboarding PPT: https://docs.google.com/presentation/d/1tlU9hWUsP44W6I0qEre0CgqrjLUaK1Vwr-hGq7phn0Q/edit#slide=id.p

**Comment by railsstudent** [comment]
I can do it after I finish the other issue.  I would like more practice on CSS.
