### ISSUE TITLE
CSS bug: "edit" button on profile page is hidden because font color is same as background color

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#655]
See screenshots.
![screen shot 2017-10-12 at 2 30 29 am](https://user-images.githubusercontent.com/4512699/31489949-44183750-aef7-11e7-980d-060106899511.jpg)
On button hover:
![screen shot 2017-10-12 at 2 30 42 am](https://user-images.githubusercontent.com/4512699/31489951-4430c130-aef7-11e7-910c-ebefd3db94ee.jpg)

If you're new to this project and need instructions about how to run the app, please check out [docs.codebuddies.org](https://docs.codebuddies.org) or our helpful onboarding PPT: https://docs.google.com/presentation/d/1tlU9hWUsP44W6I0qEre0CgqrjLUaK1Vwr-hGq7phn0Q/edit#slide=id.p

**Comment by digaant333** [comment]
Ill do it

**Comment by lpatmo** [comment]
@digaant333 Awesome, let us know if you have any questions!

**Comment by AshishkrGoyal** [comment]
@lpatmo can you please tell me that the issue is still open ??
because i want to work for it 

Thanks 👍

**Comment by lpatmo** [comment]
@AshishkrGoyal This is issue is still open. Thanks!

**Comment by angelocordon** [comment]
Is anybody tackling this issue? cc: @AshishkrGoyal

**Comment by lpatmo** [comment]
It's been a few days, so I assume @AshishkrGoyal isn't working on it anymore.

**Comment by angelocordon** [comment]
Cool - I can tackle over the weekend - @AshishkrGoyal, if you got this started, feel free to push the branch up and I can take over; no biggie if not :)
