### ISSUE TITLE
Add link to Facebook Group under "Community" nav bar

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#660]
Add link pointing to https://www.facebook.com/groups/TOPSTUDYGROUP/ below `Github`. Name this link `Facebook Groups`.

![screen shot 2017-10-14 at 10 49 28 am](https://user-images.githubusercontent.com/4512699/31578006-9a1a728a-b0cd-11e7-8c01-54fa8a23e0c5.jpg)

**Comment by ganes1410** [comment]
can i do this?

**Comment by abhishek5139190** [comment]
I can do that, just share the code.
Also i can add good icons or color them.

**Comment by lpatmo** [comment]
@ganes1410 I will mark this as claimed for you (as the first to leave a comment). Let me know if you have any questions! Docs are at `docs.codebuddies.org`.
