### ISSUE TITLE
HTML/CSS: Create a new codebuddies.org/slack page

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#667]
Right now, we are linking directly to codebuddies.slack.com from Community -> Slack on the header nav.

Let's create a new /slack route (codebuddies.org/slack), and link to this new page from the nav instead.

Relevant file to change: 
- `lib/routes.js`

Tip: follow the example of `FlowRouter.route('/faq', {`.

On this new page, add the following content:

```
Slack

Our community spends a lot of time helping each other on our Slack chatroom.

[screenshot of Slack from the #general channel]

<h3>How do I join the CodeBuddies Slack?</h3>
[pull the HTML content from the first answer on https://codebuddies.org/faq]

<h3>What is the Slack Etiquette in this community?</h3>
[pull the HTML content from https://codebuddies.org/faq]

<h3>How do you show your appreciation to someone on Slack?</h3>
We use a bot called plusplus. For example, if @hermionegranger has given me a helpful answer to a question, I might type @hermionegranger++. Think of these points as virtual cookies.

<h3>Who can create new channels on Slack?</h3>
Everyone can create private channels, but to minimize the number of inactive public channels (at one point we had over 100!), only admins can create new public channels. If you'd like a new public channel to be created -- say, for a study group around a certain topic -- please request it in the #codebuddies-meta channel.
```

If you're a new contributor, please check out docs.codebuddies.org or our onboarding PPT at https://docs.google.com/presentation/d/1tlU9hWUsP44W6I0qEre0CgqrjLUaK1Vwr-hGq7phn0Q/edit#slide=id.g265fade007_0_0!

**Comment by AshishkrGoyal** [comment]
@lpatmo can i work on this ??
Thanks in advance 😄

**Comment by railsstudent** [comment]
@AshishkrGoyal  Go ahead. Thanks.

**Comment by lpatmo** [comment]
@AshishkrGoyal Do you need any help with this issue?

**Comment by AshishkrGoyal** [comment]
@lpatmo no i am working on this and will send pr asap!!
thanks 👍

**Comment by lpatmo** [comment]
@AshishkrGoyal No worries! How's it going? Do you need any help?

**Comment by railsstudent** [comment]
If he is not working on it, I can take over.

**Comment by railsstudent** [comment]
@AshishkrGoyal A month has elapsed,  are you still working on it?
Thanks.
