### ISSUE TITLE
Send a notification to the #announcements Slack channel when a new study group is created

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#668]
In the same way that a new notification appears in #announcements whenever a new hangout is scheduled, we should send a new notification to #announcements whenever a new study group is created, ideally in this format:

A new study group has been started by @username! 

Goals:
``` Goals content ```
Description:
``` Description content ```

This is a P2 issue.

**Comment by railsstudent** [comment]
I would like to get hands-on experience of Slack API.

**Comment by railsstudent** [comment]
@lpatmo  Create Study Group modal does not have description and goal fields, add new fields in there?
Or send message to announcement channel when description tab of study group is saved? Thanks.

**Comment by lpatmo** [comment]
@railsstudent Good point -- the message should be sent when the description tab is saved!

**Comment by railsstudent** [comment]
@lpatmo  Require to  user different emoji and username than bell and CodeBuddies Alert?

**Comment by lpatmo** [comment]
@railsstudent We don't have to use the same bell emoji, no! Could be a simple sentence.

**Comment by railsstudent** [comment]
I will try to build something this evening

**Comment by distalx** [comment]
@lpatmo with current system it would be a bit difficult to track down when the first edit happens to `goal` and `description`. it would be much more feasible to send an alert on the creation of the SG.
cc @railsstudent

**Comment by railsstudent** [comment]
I am thinking of sending alert whenever either field is updated. I assume updating goal/description may attract new people to join the group.

**Comment by railsstudent** [comment]
@distalx In that case, description and goal are input fields in new SG modal.  
Please advise.

**Comment by distalx** [comment]
IMO we should send a slack alert once user create the SG. 
In alert we can add a SG title, tagline and username.
Also we could add a follow back link to SG.

In other case if we send an alert each time when someone updates the description and goal for SG that might clutter the feed. 
cc @lpatmo.

-----Original Message-----

**Comment by railsstudent** [comment]
that would work.
need to research how to add url to slack alert.

i can start to add new methods slack api and wait for final decision

**Comment by lpatmo** [comment]
Hmm, sorry, @distalx is right -- would be easier to send the Slack notification as soon as a group is created. So the announcement text would be:

```
@username has started a "TDD Python" study group! Join here: https://codebuddies.org/study-group/tdd-with-python/AshYgJsHdyo6kuCQW
```

(Feedback welcome on the text above.)

Re: URLs -- following the pattern in `server/slack/methods.js`, maybe something like:
`Meteor.absoluteUrl("study-group/" + studyGroup.slug + studyGroup._id);`

Not sure if that helps!

**Comment by railsstudent** [comment]
@lpatmo that helps a lot. thank you
