### ISSUE TITLE
CSS: Highlight the "Edit Description" error with a red border and red text if group description has not been filled out yet

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#670]
When someone creates a study group for the first time, their eyes might skip over the need to click on "Edit Description" to fill out a goal and a description for their group.

Simple UI enhancement: let's make the text red, and put a red border around the area so that anyone who has permission to edit the description area will automatically be drawn to the area.

![screen shot 2017-10-18 at 8 25 59 pm](https://user-images.githubusercontent.com/4512699/31753007-dfe63236-b442-11e7-8309-e21d879e779a.jpg)

If you're a new contributor to this project, please check out docs.codebuddies.org.

The red color is $danger-red, which is defined in _colors.scss.

**Comment by kennyhuynh125** [comment]
I can try and do this if needed!

**Comment by lpatmo** [comment]
@kennyhuynh125 I will mark it as claimed for you. Let us know if you have any questions. Thanks!

**Comment by kennyhuynh125** [comment]
@lpatmo, probably won't have time to work on this until later on, but i think to make things quicker, what file would i be able to locate the template for that page?

**Comment by lpatmo** [comment]
@kennyhuynh125 Take a look at `client/templates/study_groups/study_group_description.html`, please, and you should make the CSS change in `css/_study_groups.scss`. Color variables are defined in _colors.scss. Let me know if you have other questions!

**Comment by kennyhuynh125** [comment]
just submitted a pull request!
