### ISSUE TITLE
Make "everyone in this group can schedule a hangout" the default option in select box

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#671]
When an organizer creates a study group, it might not be entirely apparent to them that they can go to the `Settings` tab and allow every member of the group to schedule a hangout in the group. 

More likely than not, organizers will be fine with all group members starting virtual hangouts to study a topic. They'll have the option to organize specialized hangouts by only allowing admins and moderators to start hangouts, but I think we should consider making "everyone in this group can schedule a hangout" the default permission.

![screen shot 2017-10-18 at 8 49 43 pm](https://user-images.githubusercontent.com/4512699/31753738-615bf450-b447-11e7-8473-b4c2809f1001.jpg)
![screen shot 2017-10-18 at 8 49 53 pm](https://user-images.githubusercontent.com/4512699/31753739-6177a4de-b447-11e7-8e77-e942bf3815c9.jpg)

**Comment by kennyhuynh125** [comment]
I can also work on this linda!

**Comment by lpatmo** [comment]
Actually, let's hold off from changing the default. 

Reasons pointed out to me:
- Added layer of protection from spammers (email notification gets sent out to group members for each new hangout)
- We can highlight this permission in a product tour
