### ISSUE TITLE
Post text about virtual hangout and new study group creation to #facebook-group channel on Slack.

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#673]
Folks on the Facebook Group at https://www.facebook.com/groups/TOPSTUDYGROUP/ don't often get notified about newly scheduled hangouts because we keep forgetting to cross-post/announce it there. 

I previously had set up a Zapier integration that would post new messages from the #announcements channel straight to the Facebook Group, but the integration wasn't working because it got confused by our emojis and layout:

![screen shot 2017-10-18 at 11 58 12 pm](https://user-images.githubusercontent.com/4512699/31757960-411aa9c0-b460-11e7-83c7-2ca232d5b043.jpg)

(The code behind this is in `server/slack/methods.js`)

I created a new #facebook-group channel on Slack, and was thinking we could start auto-posting simple text messages to this channel. Also, this channel would be a direct link to the Facebook Group, so if there were other Facebook-specific posts we wanted to make, this would be the channel for it. 

Specs:
1) Post a simple `@username has scheduled a new hangout on "TOPIC"! [link]` message to the #facebook-group channel whenever a new hangout has been scheduled.
2) Post a simple `New study group on CodeBuddies: "STUDY GROUP NAME" [link]` message to the Slack channel whenever a new study group is created.

This isn't a priority issue by any means, but more of a nice-to-have issue.

==
New contributors: please check out docs.codebuddies.org

**Comment by BoYuanZheng** [comment]
Hi there, can I get assigned this? I'm not too familiar with Facebook or Slack APIs to be completely honest, but I think I can do it!

**Comment by BoYuanZheng** [comment]
I would like to work on this, although I have a question. Who exactly posts the content? I don't think Facebook has automated accounts or bots of any sort.

**Comment by lpatmo** [comment]
@BoYuanZheng Let us know if you have questions! We hang out in the #codebuddies-meta channel on the CodeBuddies Slack as well.

**Comment by railsstudent** [comment]
@BoYuanZheng  You can look at the last PR I made.  Slack notification is sent when a new study group is created.

**Comment by lpatmo** [comment]
@BoYuanZheng Please let me know if you're still interested in working on this issue or not! I am bumping up the priority level of this issue, to increase the likelihood of scheduled hangouts getting seen by potentially interested participants.

**Comment by railsstudent** [comment]
@lpatmo  I can work on it if @BoYuanZheng  cannot continue. Thanks.

**Comment by BoYuanZheng** [comment]
@railsstudent Ah, sorry, been far busier than I originally imagined. Please work on it instead.

**Comment by lpatmo** [comment]
Thanks for volunteering to work on it, @railsstudent -- I believe you win something like the PR MVP award this month. :)
