### ISSUE TITLE
Add "donate" link to navbar

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#674]
`good-for-beginners` issue:

1. Remove the "Open Collective" link from its position at the bottom of "Community"
2. Add a new "Donate" link to the right of "Study Groups"
3. Link to opencollective.com/codebuddies

==
New contributors: please check out docs.codebuddies.org.

**Comment by DennyScott** [comment]
I'd like to take this one on if possible.

**Comment by lpatmo** [comment]
Thanks @DennyScott!
