### ISSUE TITLE
UI: make clearer the difference between upcoming and past/completed hangouts

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#679]
Noticed that for first-time users, it's not entirely clear that the slightly-more-greyed-out hangout cards refer to events that have ended.

Maybe we should separate out the /hangouts page into two sections, like:

Upcoming Events
// upcoming hangout events

Past Events
// completed hangout events

![screen shot 2017-10-19 at 8 24 49 pm](https://user-images.githubusercontent.com/4512699/31804154-5a5e88a0-b50c-11e7-8d0c-52042e93e0ba.jpg)

**Comment by railsstudent** [comment]
I can try it.  I want to practice CSS and MongoDB.

**Comment by lpatmo** [comment]
@railsstudent Thanks! :) I believe the relevant file is `hangout_cards.html`.

**Comment by railsstudent** [comment]
I am busy with hackathon this weekend. I will tackle this issue  tonight or tomorrow

**Comment by lpatmo** [comment]
@railsstudent Thanks, no rush -- enjoy the hackathon!
