### ISSUE TITLE
Easy fix: Rename`Resources` to `Links`

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#683]
The list of resources that study group admins can compile is really a list of links; let's call it by it's name, perhaps?

Task: rename "Resources" to "Links"

![screen shot 2017-10-21 at 2 06 55 am](https://user-images.githubusercontent.com/4512699/31850313-b7d3f350-b604-11e7-9340-9b4199b6e85c.jpg)

Relevant file: 
i18n/en.i18n.json
```141:  "resources": "Resources",```

Note: let's not worry about changing the name on the backend, but we may want to update the h2 here as well:
```
client/templates/study_groups/edit_study_group_resources_modal.html
1:<template name="editStudyGroupResourcesModal">
2-  <div class="modal fade">
3-    <div class="modal-dialog modal-lg">
4-        <div class="modal-content">
5:          <form  class="updateStudyGroupResources">
6-
7-            <div class="modal-header">
8-              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
9:              <h2>Resources</h2>
```

===
New contributors: please check out [docs.codebuddies.org](http://docs.codebuddies.org). And if you'd like to claim this issue, please be sure to leave a comment here first. Thanks!

**Comment by kristinakarnitskaya** [comment]
I'll take this :)

**Comment by lpatmo** [comment]
@kristinakarnitskaya It's yours! Let us know if you have questions.
