### ISSUE TITLE
Study group admin role cannot access the 24/7 study group Hangout

### ISSUE THREAD

**Issue by dangillet** [codebuddiesdotorg/codebuddies#690]
In the PyStudy group, with the admin role, if I click on the 24/7 Hangout tab, I see the message **Please join the study group to access the 24/7 hangout.** as if I was logged out.

With the Moderator role, everything works perfectly.

**Comment by lpatmo** [comment]
@dangillet Thank you so much for catching this! I will hotfix in https://github.com/codebuddiesdotorg/codebuddies/pull/693.
