### ISSUE TITLE
See number of people in 24/7 Hangouts

### ISSUE THREAD

**Issue by dangillet** [codebuddiesdotorg/codebuddies#691]
When going in the Study Groups page, it would be great to see how many people are actually online in the 24/7 Hangout.

At the moment there is no way to know if someone is there beside connecting into it. So if we're looking for company, we would potentially have to connect in every single Hangout.

I believe those 24/7 Hangouts are not used so much for that reason. There is a lack of visibility on who is currently online in the Hangout.

**Comment by lpatmo** [comment]
Makes sense. Thanks for logging this issue, @dangillet! 

Notes: According to https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md, Jitsi gives us participantJoined, which will return the JiD of the participant. So from that I think we can calculate the number of people in a Jitsi hangout. 

Perhaps the visual display could be:

`2 people are currently in the 24/7 hangout.`

(Feedback welcome.)

**Comment by dangillet** [comment]
For the visual, I would place it in a few different places:

- In https://codebuddies.org/study-groups, I would add an icon next to the green icon showing the number of users registered in the group.
- In the study-group page (`https://codebuddies.org/study-group/<group-name>`), I would add a badge next to the 24/7 Hangout tab showing the number of people connected.
- When the tab 24/7 Hangout is selected, then I would show a message like `2 people are currently in the 24/7 hangout.`.

**Comment by lpatmo** [comment]
> In https://codebuddies.org/study-groups, I would add an icon next to the green icon showing the number of users registered in the group.

Do you mean this new icon would display the number of group members who are online at the time?

**Comment by lpatmo** [comment]
Final specs:

- [ ] In https://codebuddies.org/study-groups, add an icon next to the green icon showing the number of users registered in the group that shows a number indicating the number of people in the group's 24/7 hangout, *if there are users in there*
- [ ] In the study-group page (https://codebuddies.org/study-group/<group-name>), add a badge next to the 24/7 Hangout tab showing the number of people connected inside the Jitsi hangout.
- [ ] When the tab 24/7 Hangout is selected, show a message below the hangout frame saying "2 people are currently in the 24/7 hangout."

Reference:
https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

File to look at:
`hangout-frame.js`

**Comment by railsstudent** [comment]
I have questions about the subtasks.
For item 2 and 3,  jitsi is loaded when load button is clicked.  If  user does not click it,  number of participants cannot be calculated and event is not set up to listen to new participant joined
Do you expect to clone the jitsi logic in single study group and call it there?

For item 1, it requires individual study group to load jitsi meet and calculate a snapshot of number of participants joined 24/7 hangout.

**Comment by railsstudent** [comment]
i can work on it if i have better understanding in the jitsi, jitsi event binding and how study group passes data to hangout. Thanks.

**Comment by lpatmo** [comment]
> For item 2 and 3, jitsi is loaded when load button is clicked. If user does not click it, number of participants cannot be calculated and event is not set up to listen to new participant joined

Yes, that is true. A user needs to join the Jitsi in order to be counted.

> Do you expect to clone the jitsi logic in single study group and call it there?

I don't entirely understand this question; are you asking if Jitsi is already available on a single study group? (It is in the 24/7 hangout tab.)

> For item 1, it requires individual study group to load jitsi meet and calculate a snapshot of number of participants joined 24/7 hangout.

So in `templates/hangout/hangout-frame.js`, we have these lines:
```
    instance.api.executeCommand('displayName', data.username);
    instance.api.executeCommand('toggleChat');
    instance.api.executeCommand('avatarUrl', data.avatar);
    let jitsiParticipants = instance.api.getNumberOfParticipants();
```
... and I totally forgot that already called `instance.api.getNumberOfParticipants();`, hah! So if you add `alert(jitsiParticipants)` and then join a Jitsi on `localhost:3000`, you'll see a number in the alert.

More difficult task: figuring out how to pass that `jitsiParticipants` variable outside of the `hangout-frame` template to display it on the study-groups page, with multiple numbers showing up if multiple study groups have active participants.

Probably easier task: display the number on the single study group page's 24/7 tab itself in parentheses (like with `Members (5)`).

**Comment by railsstudent** [comment]
> Do you expect to clone the jitsi logic in single study group and call it there?

> I don't entirely understand this question; are you asking if Jitsi is already available on a single study group? (It is in the 24/7 hangout tab.)

Yes.  The tab resides in single_study_group.js and how can single_study_group.js obtains the value of jitsiParticipants variable in hangout_frame.js and display it?

If I listen to participantJoined and participantLeft events and update jitsiParticipants (make it a reactiveVar), will the tab update the value in real time?

instance.api.addEventListener('participantJoined', () => {
     jitsiParticipants += 1;
});

instance.api.addEventListener('participantLeft', () => {
     jitsiParticipants -= 1;
});

> For item 1, it requires individual study group to load jitsi meet and calculate a snapshot of number of participants joined 24/7 hangout.

> More difficult task: figuring out how to pass that `jitsiParticipants` variable outside of the `hangout-frame` template to display it on the study-groups page, with multiple numbers showing up if multiple study groups have active participants.

Yes, that's is the part I find difficult. In all_study_group.js, my_study_group.js,  we have to define helper method to find the hangout id of each study group and then call jitsi api to get number of participants.
Will the value change in real-time if other member joins the hangout?

> Probably easier task: display the number on the single study group page's 24/7 tab itself in parentheses (like with `Members (5)`).

Same as my question above. The tab resides in single_study_group.js and how can single_study_group.js obtains the value of jitsiParticipants variable in hangout_frame.js and display it?

I hope my questions are valid and we can collaborate to find a feasible solution to tackle this request. Thanks.

**Comment by lpatmo** [comment]
@railsstudent I believe we can use session variables (e.g. Session.set() and Session.get()) to pass the data between different javascript files. 

@distalx and @sergeant-q -- do you have any thoughts?

**Comment by railsstudent** [comment]
@lpatmo I can research on Session.set() and Session.get(). I am new to MeteorJS

**Comment by railsstudent** [comment]
@lpatmo @distalx @sergeant-q  I think Session.set and Session.get will work for task 2 and 3. 
hangout-frame.js set a session variable for 24/7 and single-study-group.js get notifies when changes to the session variable occurs. Then tab in single_study_group.js is updated to show new variable.

For task 1, this is my guess here. hangout-frame.js update a session variable that is array of 24/7 hangout participants. Study groups page gets updated and rerender the page.  
Similarly, there is an array of 24/7 hangout participants for my study group page and the page is rerendered by the same merchanism.
God, so many session variables require to be updated.
Please advise. Thanks.

**Comment by railsstudent** [comment]
@distalx , so update participants_count in event listener too?

nstance.api.addEventListener('participantJoined', () => {
AppStats.upsert({hangout_id: room}, { $inc: { participants_count: +1 } });
});

instance.api.addEventListener('participantLeft', () => {
AppStats.upsert({hangout_id: room}, { $inc: { participants_count: -1 } });
});

In other template js, subscribe AppStats collection?  
<templatename>.autorun(() => {
     subscribe AppStats?
}) 

thanks.

**Comment by distalx** [comment]
@railsstudent, 

> so update participants_count in event listener too?
That was just a rough example, Jitsi's event listener might be more suitable for this use case.
But for some reason if event listener don't work as expected we could always fallback to blaze api.

> In other template js, subscribe AppStats collection?
Yes.

**Comment by railsstudent** [comment]
@distalx @lpatmo Thanks.  
I will arrange time to work on it. Given the complexity, please expect a lot of questions from me in slack

**Comment by distalx** [comment]
With the current implementation of PR #719 we are capturing following user actions
`join hangout` when user clicks on `click to load hangout button`.  `(participant++)`
`leave hangout` when user goes to the different url. `(participant --)`

When participant leaves the hangout by closing a browser tab (firefox) in which hangout is running or browser it self, those actions are not being captured. and that could possible mean dealing with steal data. we won't be able to keep the accurate tally of participants, So How to remove those ghost participants !?

cc @sergeant-q, @lpatmo, @railsstudent

**Comment by sergeant-q** [comment]
@distalx I haven't reviewed the spec on this feature but is the issue with having a _real-time/up-to-date_ count of participants while the hangout is _active_ or at the conclusion of the hangout?

In other words, do we care how many participants joined the study group or are currently in the active hangout?
