### ISSUE TITLE
Timezone aware event

### ISSUE THREAD

**Issue by soueuls** [codebuddiesdotorg/codebuddies#695]
**Do you want to request a feature or report a bug?**
A feature

**What is the current behavior?**
Hangouts are generally (always?) given in CEST timezone.

**What is the expected behavior?**
Hangouts should ideally be stored in UTC but displayed in a timezone-aware format. moment-timezone makes it very easy (it uses different strategies to detect the user's local timezone)

**Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug)**
All

**Comment by sergeant-q** [comment]
I thought this issue was brought up a few times in the past? I can't recall what was discussed or decided on?

**Comment by lpatmo** [comment]
> Hangouts are generally (always?) given in CEST timezone.

@soueuls Is your computer clock currently in CEST time? On mine, events show up in PDT time. We are also using the `moment` library already. :) 

If you change your computer clock time, the time of the event/hangout will automatically get converted to the respective timezone. 

Do you have any ideas about how we can better improve the UI to make it obvious that the time has been automatically converted to the user's timezone already?

**Comment by soueuls** [comment]
I took the time to verify, and you are completely right.

I was used to moment showing timezone such as "Europe/Paris" but you are using zone, thus it shows CEST.

That's completely my fault, I was not aware of this notations therefore CodeBuddies currently support local timezone, I am closing this.
