### ISSUE TITLE
HTML/CSS: Make "Click to load hangout" text green

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#697]
H/t @bethanyg for raising up this issue. When a user unfamiliar with how to join a hangout RSVPs to an event goes to the hangout page, they've sometimes gotten confused and missed the "Click to load the hangout" link to load the hangout, and clicked on the Google Hangout "start" button instead because it's bright green.

As a first step, let's turn `<a class="load-hangout display-inline">Click to load the hangout</a>` green -- the green color as defined in _colors.scss. 

I will file the second step (moving the Google Hangout "Start" button over to the side) as a separate issue.

If you'd like to work on this issue, please:
1) leave a comment
2) check out docs.codebuddies.org

Here is a screenshot of what a user sees when they've RSVPed and are on a page for a live hangout, before they've clicked the image to join:

![screen shot 2017-10-29 at 10 32 31 pm](https://user-images.githubusercontent.com/4512699/32156341-fd7965ba-bcf9-11e7-9817-1f0f2fae7e23.jpg)

For the record, here is an (example) screenshot of what a user will see after they've clicked to join the hangout correctly:

![screen shot 2017-10-29 at 10 40 24 pm](https://user-images.githubusercontent.com/4512699/32156392-4717b85c-bcfa-11e7-84b1-511303138cd4.jpg)

**Comment by angelocordon** [comment]
What actually gets invoked when `Click to Load Hangout` is clicked? Wondering if it's easy enough to wrap in a function and load the hang out on page load? 

I didn't actually realize that the text was clickable. So not necessarily making the text color green could  100% solve the issue - I think it may actually make it more confusing. I'd suggest turning it to a primary button instead and organizing the CTAs on the page?

+ I think _ideally_ the UX of the page would be that the hang out automatically loads.
+ `If you're seeing a blank screen` text should be moved to an info alert.
+ `End Hangout Manually` should be a secondary styled button.

I'm almost inclined to remove the Google Hangouts link completely - or discuss it at a deeper level in a separate issue (or here is fine as well). But I think while I understand the reasons why we have it there, I'm not actually sure why we still need it and is kind of broken - when members are using Jitsi, but then another person in the audience wants to use Hangouts and clicks on that button but nobody is in the Google Hangouts video.

**Comment by lpatmo** [comment]
Thanks for your questions/thoughts, @angelocordon! Glad nobody picked up this issue yet. :) 

> I think ideally the UX of the page would be that the hang out automatically loads.

The technical issue I faced when I tried to implement this the first time around (having the hangout load automatically when the hangout time arrives) is that if I already have this page open, the page would need to reload before the hangout frame could load. So it was a technical barrier, not a user design barrier. 

I'm not sure if'd want the hangout to load as soon as a user RSVPed and landed on the page, before the time of the event arrived. Maybe it wouldn't be so bad? [Needs more discussion]

> If you're seeing a blank screen text should be moved to an inyo alert.
YES, good suggestion -- let's do that. I believe the class to use is `<div class="alert-warning">`

> End Hangout Manually should be a secondary styled button.
By secondary styled button do you mean black on white -- like the "duplicate" button on the left? So it's not as glaring? :) 

So the revised specs for this issue: 
1) Turn the "Click to load the hangout" text into a button (white color on blue background)
2) Turn `if you're seeing a blank screen` into an info alert
3) Make the "End hangout manually" button less red. (Btw, it will only show up for site admins or the creator of the hangout.)

Please let me know if that's accurate.

**Comment by railsstudent** [comment]
I will take over and tackle it next week.
