### ISSUE TITLE
HTML: Move "Want to use Google Hangouts?" button over to the left sidebar.

### ISSUE THREAD

**Issue by lpatmo** [codebuddiesdotorg/codebuddies#698]
Part II of https://github.com/codebuddiesdotorg/codebuddies/issues/697. When a user unfamiliar with how to join a hangout RSVPs to an event goes to the hangout page, they've sometimes gotten confused and missed the "Click to load the hangout" link to load the hangout, and clicked on the Google Hangout "start" button instead because it's bright green.

Let's move the "want to use Google Hangouts instead?" text and the button over to the left sidebar, above the "HANGOUT TIPS" section.

Let's call this section "HANGOUT ALTERNATIVES" and underneath it:
Google Hangouts: [button]

If you'd like to work on this issue, please:

1. leave a comment
2. check out docs.codebuddies.org

Here is a screenshot of what a user sees when they've RSVPed and are on a page for a live hangout, before they've clicked the image to join:

![image](https://user-images.githubusercontent.com/4512699/32156482-f2e5d2c2-bcfa-11e7-8810-b155940fb00f.png)

For the record, here is an (example) screenshot of what a user will see after they've clicked to join the hangout correctly:

![image](https://user-images.githubusercontent.com/4512699/32156478-ed51041c-bcfa-11e7-9e71-ef67e73cf6d2.png)

**Comment by thivatm** [comment]
I would like to work on this project

**Comment by lpatmo** [comment]
@thivatm I will mark this as `claimed` for you. Thanks!
