### ISSUE TITLE
Hangouts:  Deleting a Scheduled Hangout Triggers a <500> From the Server

### ISSUE THREAD

**Issue by BethanyG** [codebuddiesdotorg/codebuddies#704]
On MacOS Sierra, using latest Chrome Browser build.

Steps:
1)  Go to www.codebuddies.org and create a Hangout
2)  Once the Hangout is created, click the [**edit**] menu, and select [**delete**]

Expected:  Hangout is successfully deleted.  

Actual:   ![screen shot 2017-11-07 at 6 28 56 pm](https://user-images.githubusercontent.com/5923094/32528746-9477a35a-c3e9-11e7-997f-ed3370a8a0f0.png)

_..and the Hangout is **not** deleted._

**Comment by distalx** [comment]
@BethanyG  Thanks for filing this issue.
