### ISSUE TITLE
make use of external-link icon

### ISSUE THREAD

**Issue by distalx** [codebuddiesdotorg/codebuddies#718]
Currently, We have several external links `sponsor us, facebook, slack, github, medium, etc ...`
if we use external-link icon to distinguish these links from normal link, that could improve the user-experience.

external-link icon :
http://fontawesome.io/icon/external-link/

**Comment by railsstudent** [comment]
Do you refer to the hyperlinks in the footer or the menu items in navigator bar?
The menu items in the community menu are ready using font-awesome icons. 
Please clarify. Thanks.

**Comment by distalx** [comment]
I think all the external links, could use this icon. if any external link already uses some icon, then that could be replace with external-link icon.
<img width="145" alt="screen shot 2017-11-18 at 8 00 21 pm" src="https://user-images.githubusercontent.com/11193792/32981442-e7469284-cc9b-11e7-876f-86f5e08a91ad.png">

cc @lpatmo
