### ISSUE TITLE
scrollbars visible

### ISSUE THREAD

**Issue by nalbina** [codebuddiesdotorg/codebuddies#726]
Hey there, I am on Windows 10, latest Chrome.
When I browse codebuddies.org/hangouts I see the scrollbars on each card which is not so pretty.

![scrollbars](https://i.imgur.com/gCqG4jz.png)

Does anybody else see this?

**Comment by railsstudent** [comment]
@nalbina  I see it in my linux machine.
It is CSS issue.  overflow: scroll makes scrollbar always visible.  Change it overflow: auto will make the scrollbar to appear when the topic and description in the hangout card is too long

**Comment by lpatmo** [comment]
Thanks for filing, @nalbina, and @railsstudent for fixing.
