### ISSUE TITLE
Feature Request: Add to Calendar

### ISSUE THREAD

**Issue by tracypholmes** [codebuddiesdotorg/codebuddies#739]
Before you open an issue, please check if a similar issue already exists or has been closed before. Also please remember that you can also get help in the [#codebuddies-meta channel on the CodeBuddies Slack](https://codebuddiesmeet.slack.com/messages/codebuddies-meta/). (If you are not a member, you can get your invite from [here](http://codebuddiesmeet.herokuapp.com/).

Do you want to request a feature or report a bug? Feature

What is the current behavior? Once you RSVP, the only way a person currently receives a notification is by email. You also get a reminder 24 hours prior to the event start.

What is the expected behavior? Requesting we add the ability to "Add to Calendar" in the popup once your RSVP is confirmed. Example: 
![addtocalendar](https://user-images.githubusercontent.com/12778804/33244151-b0513c6c-d2b7-11e7-8595-dd07663b068f.png)

In my specific instance, the event reminder went to my spam folder. As I'd not manually added it to my calendar, I missed the Hangout. 

Which browser / OS are affected by this issue? (An *isolated* way to reproduce the bug): All. This is default behavior.

**Comment by lpatmo** [comment]
Thank you for filing this issue, @tracypholmes! ++ to the mockup. Perhaps we should also have those "add to google cal/ical" buttons on the hangout page itself, after the popup is closed.

**Comment by lpatmo** [comment]
This is probably the API we want for Google Calendar: https://developers.google.com/google-apps/calendar/v3/reference/events/insert

**Comment by railsstudent** [comment]
To use google calendar api,  user has to login gmail and give permission to codebuddies.org to add event to calendar on user's behalf.

**Comment by lpatmo** [comment]
Hmm, or maybe we can do what Meetup.com does for Google Calendar and pass parameters into a URL string? It doesn't look like they use an API key, though I could be wrong. 

For example, if you click on this link:
https://www.google.com/calendar/event?action=template&ctext=each+fri+9am-2pm+for+2+weeks+test+at+home
(Credit: https://webapps.stackexchange.com/questions/43650/correct-url-for-google-calendar-quick-add)

**Comment by railsstudent** [comment]
The above link  opens log in dialog of google and prompts password

**Comment by railsstudent** [comment]
https://github.com/carlsednaoui/add-to-calendar-buttons
https://github.com/tardate/jquery.addtocalendar
http://keith-wood.name/icalendar.html

JQuery plugins add event to calendar.

**Comment by lpatmo** [comment]
Nice! Thanks for finding. I like the easy support for multiple calendars, although I'm a little wary of one of the plugins being out of date or not compatible with the version of jQuery we're using. Perhaps just need to test.

Re: https://www.google.com/calendar/event?action=template&ctext=each+fri+9am-2pm+for+2+weeks+test+at+home -- it'll prompt a password if you're not logged into Google or are opening it up in a fresh incognito window; I believe this will be true for all cases.

**Comment by tracypholmes** [comment]
@lpatmo re: _"Perhaps we should also have those "add to google cal/ical" buttons on the hangout page itself, after the popup is closed."_ I like that idea! It makes it very convenient. 
I'll help you all where I can, especially if you need me for testing. So, just let me know.

**Comment by railsstudent** [comment]
https://calendar.google.com/calendar/r/eventedit?text=Your+Event+Name&dates=20140127T224000Z/20140320T221500Z&details=For+details,+link+here:+http://www.example.com&location=Waldorf+Astoria,+301+Park+Ave+,+New+York,+NY+10022&sf=true&output=xml

this link opens  a page with event details. Now I am worry about timezone that requires some testing.

**Comment by lpatmo** [comment]
@railsstudent This is what I see:

![screen shot 2017-12-25 at 12 01 37 am](https://user-images.githubusercontent.com/4512699/34333090-db8ba8bc-e906-11e7-8553-8f0f6dc3732f.jpg)

**Comment by railsstudent** [comment]
@lpatmo  Yes.  User clicks the link to open it in a new tab and save the hangout event. 
No external library is required.

**Comment by lpatmo** [comment]
@railsstudent I meant to say I shared the screenshot as a helper for timezone testing. :) My google calendar is in EST time and I saw 5:40pm to 6:15pm.

**Comment by railsstudent** [comment]
<img width="867" alt="screen shot 2017-12-27 at 2 55 11 pm" src="https://user-images.githubusercontent.com/1159649/34373456-15269e2c-eb16-11e7-9c50-e9e2d872dc75.png">

@lpatmo  My Start time is 13hrs ahead of you that is expected.  However, my end time is only 12hrs ahead that is wrong.

**Comment by lpatmo** [comment]
@railsstudent Thank you for the link! I've submitted a PR here: https://github.com/codebuddiesdotorg/codebuddies/pull/755

My HTML:
             <a href="https://calendar.google.com/calendar/r/eventedit?text={{topic}}{{#if group}} ({{group.title}}{{/if}})&details={{description}}&location=https://meet.jit.si/cb{{_id}}&dates={{getHangoutGoogleCalendarDate start}}T{{getHangoutGoogleCalendarTime start}}/{{getHangoutGoogleCalendarDate end}}T{{getHangoutGoogleCalendarTime end}}" target="_blank" class="btn btn-cb2"><i class="fa fa-calendar" aria-hidden="true"></i> Add to Google Calendar</a>

I've put more details/screenshots on the pull request. Feedback welcome -- thank you. I'm not entirely satisfied with how it works right now, but functionally it should work, and I didn't notice any issues with timezones when I changed my computer clock timezone and played around with different dates.

**Comment by lpatmo** [comment]
https://github.com/codebuddiesdotorg/codebuddies/pull/755 has been merged into production. If anyone has suggestions for improvement, feel free to suggest! I realize we don't support iCal yet.
