### ISSUE TITLE
Immune system for Codebuddies.

### ISSUE THREAD

**Issue by distalx** [codebuddiesdotorg/codebuddies#76]
I think we should have some sort of filtering mechanism to naturally push out spammers, bad actors.

**Comment by lpatmo** [comment]
We can implement this by giving some users "moderator" status, and give them permission to remove (and possibly edit) posts.

**Comment by distalx** [comment]
That would be great too,
But I'm thinking about a system which can identify a negative actors, by it self. And also a user could  able to report or flag those kinds of activities.

By Immune system I mean a system which can _differentiate_ between good and bad.
For that we need some rules for the each user input, based on that rule we can assign some value to each input.

```
IF Topic of the hangout has less than 30 char -1 Else +1
IF Description has more than 2 links (urls) -1 Else +1
IF use of abusive words in topic or description -5 Else +1
```

IF hangout score is less than -2 , a moderator should be alerted and that hangout should be flagged.
and only make those hangout public if moderator find it appropriate.

Normal user won't be able to see these points, these will be just for system use only.

I got this idea from https://www.discourse.org/ , They have some sort of Similar system of their own which  elegantly runs  behind the curtain without hinting away it's existence to the normal user.

**Comment by foxiae** [comment]
@distalx I think this would be a good addition to have with the proposed moderator settings. Though I think we should give some thought as to what those flags should be. 

Should users be notified that their hangouts need to be formatted a certain way (i.e., no foul language, must contain a certain length, etc)?

**Comment by sebbel** [comment]
Mistakes happen by accident. I would give feedback to the user why his hangout or hangout description was altered/removed/flagged
