### ISSUE TITLE
Signed on as a new user and wanted to change the user name, noticed I was unable to. Thought I would delete the account and setup an email with a username that I wanted but it appears that the delete window is not working. The button does indicate that it has been clicked.

### ISSUE THREAD

**Issue by otawestside** [codebuddiesdotorg/codebuddies#781]
Delete window is not working.

**Comment by angelocordon** [comment]
Thanks for posting @otawestside - though I think this may be a duplicate or with the general direction as #749. Going to close this issue to keep our issues logs clean 👍

**Comment by otawestside** [comment]
I think the duplicate only mentions the situation about not being able to edit the username.
I wanted to add that the delete account page/window is non-functional.

**Comment by otawestside** [comment]
Hi Angelo,

Appreciate the reply.  My apologies, don't know how to look up past posts.
Kinda new at this.
I think the duplicate only mentions the situation about not being able to
edit the username.
I wanted to add that the delete account page/window is non-functional.
Should I re-post with only the delete issue?
thx

**Comment by angelocordon** [comment]
hi @otawestside - 

gotcha - yes please, it would helpful to edit or make a new issue talking about deleting an account  💪 

Thanks!
