### ISSUE TITLE
Hangout Details Page - Design/Layout Update Request

### ISSUE THREAD

**Issue by sergeant-q** [codebuddiesdotorg/codebuddies#80]
I think we need to add a little more "life" to the hangout details page.  It's very basic right now and there's no organization around the details.  

![image](https://cloud.githubusercontent.com/assets/1451729/14051884/40559158-f283-11e5-9fee-e2d862d29a60.png)

@adachiu any chance in getting your help mocking something up? :)

I'm thinking the layout should separate/highlight the host, participants and date of when the hangout will occur. Maybe we can _pull_ in the **host's** details from their user profile and add it to this page so they know a little more about them as an example.

**Comment by sergeant-q** [comment]
@lpatmo I think this has been already been implemented correct? Can we close this issue?

**Comment by lpatmo** [comment]
I started working on a redesign of the hangout post page.

Here's what it currently looks like:
![cb_hangout_old](https://user-images.githubusercontent.com/4512699/29992335-424bfcb8-8f4e-11e7-9554-2bdb0b767f91.png)

Here's the redesign:
![cb_hangout_redesign1](https://user-images.githubusercontent.com/4512699/29992326-1c320bf8-8f4e-11e7-90bc-81add69affc2.png)
![cb_hangout_redesign2](https://user-images.githubusercontent.com/4512699/29992325-1c2d9622-8f4e-11e7-949f-27287c11bb98.png)

I thought it would be better if we un-hid the "edit" and "duplicate" features -- and also constrained all the meta information on a sidebar to the left. 

Thoughts/feedback welcome!

**Comment by sergeant-q** [comment]
@lpatmo I think this design looks great!

**Comment by lpatmo** [comment]
Thank you @sergeant-q! :) I got some feedback that the Jitsi preview/diagram was too busy/distracting/had too many words, so here is another update to the design:

![cb_hangout_redesign5](https://user-images.githubusercontent.com/4512699/29998354-a015b41c-8fdd-11e7-90ba-baf1afd47693.png)
