### ISSUE TITLE
Hangout RSVP 10 Participants Cap

### ISSUE THREAD

**Issue by wuworkshop** [codebuddiesdotorg/codebuddies#84]
Since Google Hangouts has a cap of 10 users, should we limit RSVPs to 10? Or maybe there should be some sort of disclaimer info somewhere about the Hangouts cap?

**Comment by adachiu** [comment]
@wuworkshop How about letting users choose the amount of participants? up to 10 allowed since it's the limit.

**Comment by pdotsani** [comment]
@wuworkshop @adachiu maybe a dropdown on the form we're using to create the hangout RSVP, then add that data into the body of the api call?

**Comment by lpatmo** [comment]
@pdotsani Do you mean when a host creates a hangout, they'll see an extra dropdown where they can choose the # of participants?

**Comment by adachiu** [comment]
@pdotsani @lpatmo that works. Having the dropdown in the form to indicate participant limit.

**Comment by sergeant-q** [comment]
So a couple things that come to mind. Not all people who RSVP will actually show up to a hangout session. Giving the host the ability to choose the number of participants won't enforce anything on the backend.

A couple of suggestions:
 - provide a notice on the hangout list and single post view that the max participants limit is 10. First come, first serve. 
 - keep count of RSVP'd participants on the server side and disallow any new ones once it reaches 10. 

As noted earlier people may or may not show up even if they RSVP so the hope is that if they don't plan to attend to un-RSVP.

**Comment by adachiu** [comment]
Previously discussed with @lpatmo about a ranking point system where if somebody doesn't attend an RSVP-ed hangout, they would have -1 point—this feature isn't high priority at the moment, and still needs more discussion.

I like the first-come-first-serve concept. However, there may be some anxiety for those who are eager to get in to the hangout!

**Comment by longp** [comment]
Is anyone working on this?

**Comment by lpatmo** [comment]
@longp No one is working on this issue (capping the # of attendees on each post to 10). Are you interested in it?

**Comment by longp** [comment]
Yeah I am interested, Just cloned it and will be poking around now

**Comment by wuworkshop** [comment]
Since Google is deprecating its hangouts API, and it looks like we're considering Jitsi which claims to support "unlimited users", this issue can be closed now.

@longp Hopefully you haven't spent too much time on this one. ^^'
