### ISSUE TITLE
Creating a Resource Page

### ISSUE THREAD

**Issue by oliikit** [codebuddiesdotorg/codebuddies#87]
Codebuddiesdotorg contains repos of useful resources and people pin useful resources on Slack channels. Can we add a page with useful resources for learners?

**Comment by distalx** [comment]
@foxiae 
We have something like that incase if you missed it .. 
https://github.com/codebuddiesdotorg/crowdsourced-resources
But definitely we can add this to our app and make it more accessible.

Would be a good idea if ppl can submit the resources they find useful ? But then we'll also need some sort of filtering and monitoring system for that.

**Comment by foxiae** [comment]
@distalx that's the repo I was referring to. Is there a way we can push the .md to the site? That way, if people want to add something, it's somewhat controlled?

**Comment by distalx** [comment]
I see, There are many ways to skin a cat. Let's see what other buddies feels about it.

**Comment by lpatmo** [comment]
@foxiae Were you suggesting that https://github.com/codebuddiesdotorg/crowdsourced-resources be a page on the website itself?

**Comment by techtolentino** [comment]
Is this still wanted or needed?

**Comment by lpatmo** [comment]
I think this feature is deprioritized for now, but we may want it in the future.

**Comment by lpatmo** [comment]
Restarting the conversation about this feature idea... 

What should this resources feature look like?

Should we have a codebuddies.org/resources page, with:
- a submit button the top right?
- the ability to add links under certain pre-defined categories
- or maybe the ability to add links with newly defined categories?
- Should other users be able to upvote your links?
- How should these resources get tied back to study groups or hangouts created on the main site?
- Should people be allowed to leave reviews of these resources, or is that too ambitious of a feature for this project?
- What's the MVP we can make that can make a Resources page useful and widely-used without making it too time-consuming to code?

**Comment by lpatmo** [comment]
Closing this. In Study Groups, people will be able to add links/resources to groups.

We'll also discuss resource recommendations on the Discourse forum.
